//! Inspectable outcome of one flow runner execution.

use std::fmt::Write as _;
use std::time::Duration;

use crate::Role;

/// Protocol-neutral recovery observations collected during one flow run.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RecoveryMetrics {
    timeout_events: u64,
    pto_firings: u64,
    packets_declared_lost: u64,
    regenerated_transmits: u64,
    exact_replay_transmits: u64,
}

impl RecoveryMetrics {
    /// Return the number of protocol timeout events handled by the flow.
    pub const fn timeout_events(&self) -> u64 {
        self.timeout_events
    }

    /// Return the number of probe-timeout firings reported by a protocol driver.
    pub const fn pto_firings(&self) -> u64 {
        self.pto_firings
    }

    /// Return the number of packets a protocol driver declared lost.
    pub const fn packets_declared_lost(&self) -> u64 {
        self.packets_declared_lost
    }

    /// Return the number of fresh recovery transmits generated by a protocol driver.
    pub const fn regenerated_transmits(&self) -> u64 {
        self.regenerated_transmits
    }

    /// Return the number of exact-byte replay transmits observed by the flow.
    pub const fn exact_replay_transmits(&self) -> u64 {
        self.exact_replay_transmits
    }

    pub(crate) fn add_timeout_events(&mut self, count: u64) {
        self.timeout_events = self.timeout_events.saturating_add(count);
    }

    pub(crate) fn add_pto_firings(&mut self, count: u64) {
        self.pto_firings = self.pto_firings.saturating_add(count);
    }

    pub(crate) fn add_packets_declared_lost(&mut self, count: u64) {
        self.packets_declared_lost = self.packets_declared_lost.saturating_add(count);
    }

    pub(crate) fn add_regenerated_transmits(&mut self, count: u64) {
        self.regenerated_transmits = self.regenerated_transmits.saturating_add(count);
    }

    pub(crate) fn add_exact_replay_transmits(&mut self, count: u64) {
        self.exact_replay_transmits = self.exact_replay_transmits.saturating_add(count);
    }

    const fn is_empty(&self) -> bool {
        self.timeout_events == 0
            && self.pto_firings == 0
            && self.packets_declared_lost == 0
            && self.regenerated_transmits == 0
            && self.exact_replay_transmits == 0
    }
}

/// Terminal status recorded in a [`FlowReport`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FlowOutcome {
    /// The flow reached a terminal step.
    Completed,
    /// The current state did not receive a matching packet before the timeout.
    TimedOut,
    /// The configured bound did not allow another iteration.
    BoundExhausted,
    /// The runner stopped on an error that could still be represented as a report.
    Error(String),
}

/// Inspectable execution report returned by [`crate::Runner`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FlowReport {
    flow_name: String,
    role: Role,
    dry_run: bool,
    visited_states: Vec<String>,
    sent_count: usize,
    received_count: usize,
    payload_protocol: Option<String>,
    bytes_sent: usize,
    bytes_received: usize,
    received_payload: Vec<u8>,
    recovery: RecoveryMetrics,
    tcp_snd_nxt: Option<u32>,
    tcp_rcv_nxt: Option<u32>,
    transitions_taken: Vec<String>,
    iterations: u64,
    elapsed: Duration,
    outcome: FlowOutcome,
    context_snapshot: String,
}

impl FlowReport {
    /// Create a flow report from collected runner state.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        flow_name: impl Into<String>,
        role: Role,
        dry_run: bool,
        visited_states: Vec<String>,
        sent_count: usize,
        received_count: usize,
        transitions_taken: Vec<String>,
        iterations: u64,
        elapsed: Duration,
        outcome: FlowOutcome,
        context_snapshot: impl Into<String>,
    ) -> Self {
        Self {
            flow_name: flow_name.into(),
            role,
            dry_run,
            visited_states,
            sent_count,
            received_count,
            payload_protocol: None,
            bytes_sent: 0,
            bytes_received: 0,
            received_payload: Vec::new(),
            recovery: RecoveryMetrics::default(),
            tcp_snd_nxt: None,
            tcp_rcv_nxt: None,
            transitions_taken,
            iterations,
            elapsed,
            outcome,
            context_snapshot: context_snapshot.into(),
        }
    }

    /// Return a report with protocol-neutral application payload observations attached.
    ///
    /// Callers should supply payload bytes and counts recorded by their flow context. In
    /// particular, protected protocols must not derive these observations by inspecting wire
    /// payloads.
    pub fn with_protocol_payload(
        mut self,
        protocol: impl Into<String>,
        bytes_sent: usize,
        received_payload: impl Into<Vec<u8>>,
    ) -> Self {
        let received_payload = received_payload.into();
        self.payload_protocol = Some(protocol.into());
        self.bytes_sent = bytes_sent;
        self.bytes_received = received_payload.len();
        self.received_payload = received_payload;
        self
    }

    /// Return a report with TCP payload byte counters attached.
    ///
    /// This compatibility builder delegates to the protocol-neutral payload builder.
    pub fn with_tcp_payload(self, bytes_sent: usize, received_payload: impl Into<Vec<u8>>) -> Self {
        self.with_protocol_payload("tcp", bytes_sent, received_payload)
    }

    /// Return a report with protocol-neutral recovery observations attached.
    pub fn with_recovery_metrics(mut self, recovery: RecoveryMetrics) -> Self {
        self.recovery = recovery;
        self
    }

    /// Return a report with final TCP sequence tracking attached.
    pub const fn with_tcp_state(
        mut self,
        tcp_snd_nxt: Option<u32>,
        tcp_rcv_nxt: Option<u32>,
    ) -> Self {
        self.tcp_snd_nxt = tcp_snd_nxt;
        self.tcp_rcv_nxt = tcp_rcv_nxt;
        self
    }

    /// Return the executed flow name.
    pub fn flow_name(&self) -> &str {
        &self.flow_name
    }

    /// Return the executed flow role.
    pub const fn role(&self) -> Role {
        self.role
    }

    /// Return true when this run used an offline dry-run binding.
    pub const fn is_dry_run(&self) -> bool {
        self.dry_run
    }

    /// Return state names in the order the runner entered them.
    pub fn visited_states(&self) -> &[String] {
        &self.visited_states
    }

    /// Return the final state name recorded by the runner.
    pub fn final_state(&self) -> Option<&str> {
        self.visited_states.last().map(String::as_str)
    }

    /// Return the number of packets sent or planned.
    pub const fn sent_count(&self) -> usize {
        self.sent_count
    }

    /// Return the number of packets received from the capture source.
    pub const fn received_count(&self) -> usize {
        self.received_count
    }

    /// Return the protocol label associated with application payload accounting.
    pub fn payload_protocol(&self) -> Option<&str> {
        self.payload_protocol.as_deref()
    }

    /// Return application payload bytes sent by this run.
    pub const fn bytes_sent(&self) -> usize {
        self.bytes_sent
    }

    /// Return application payload bytes received by this run.
    pub const fn bytes_received(&self) -> usize {
        self.bytes_received
    }

    /// Return received application payload accumulated by this run.
    pub fn received_payload(&self) -> &[u8] {
        &self.received_payload
    }

    /// Return the recovery observations attached to this report.
    pub const fn recovery_metrics(&self) -> &RecoveryMetrics {
        &self.recovery
    }

    /// Return the final TCP send-next value, if this run tracked one.
    pub const fn tcp_snd_nxt(&self) -> Option<u32> {
        self.tcp_snd_nxt
    }

    /// Return the final TCP receive-next value, if this run tracked one.
    pub const fn tcp_rcv_nxt(&self) -> Option<u32> {
        self.tcp_rcv_nxt
    }

    /// Return transition descriptions in the order they fired.
    pub fn transitions_taken(&self) -> &[String] {
        &self.transitions_taken
    }

    /// Return the number of completed flow iterations.
    pub const fn iterations(&self) -> u64 {
        self.iterations
    }

    /// Return elapsed run time.
    pub const fn elapsed(&self) -> Duration {
        self.elapsed
    }

    /// Return the terminal run outcome.
    pub const fn outcome(&self) -> &FlowOutcome {
        &self.outcome
    }

    /// Return the final packet-context summary captured by the runner.
    pub fn context_snapshot(&self) -> &str {
        &self.context_snapshot
    }

    /// Return a compact one-line description of this run.
    pub fn summary(&self) -> String {
        let mut summary = format!(
            "FlowReport '{}' ({:?}, dry_run={}): {:?}, state_trace={}, final_state={}, sent={}, received={}, bytes_sent={}, bytes_received={}, transitions={}, iterations={}, elapsed={:?}",
            self.flow_name,
            self.role,
            self.dry_run,
            self.outcome,
            self.state_trace(),
            self.final_state().unwrap_or("none"),
            self.sent_count,
            self.received_count,
            self.bytes_sent,
            self.bytes_received,
            self.transitions_taken.len(),
            self.iterations,
            self.elapsed,
        );
        if let Some(protocol) = self.payload_protocol() {
            let _ = write!(summary, ", payload_protocol={protocol}");
        }
        write_recovery_summary(&mut summary, &self.recovery);
        summary
    }

    /// Return a multi-line inspectable view of this run.
    pub fn show(&self) -> String {
        let mut output = String::new();

        let _ = writeln!(output, "FlowReport '{}'", self.flow_name);
        let _ = writeln!(output, "  role: {:?}", self.role);
        let _ = writeln!(output, "  dry-run: {}", self.dry_run);
        let _ = writeln!(output, "  outcome: {:?}", self.outcome);
        let _ = writeln!(output, "  iterations: {}", self.iterations);
        let _ = writeln!(output, "  elapsed: {:?}", self.elapsed);
        let _ = writeln!(
            output,
            "  packets: sent={}, received={}",
            self.sent_count, self.received_count
        );
        let _ = writeln!(
            output,
            "  final state: {}",
            self.final_state().unwrap_or("none")
        );
        let _ = writeln!(
            output,
            "  payload bytes: sent={}, received={}",
            self.bytes_sent, self.bytes_received
        );
        if let Some(protocol) = self.payload_protocol() {
            let _ = writeln!(output, "  payload protocol: {protocol}");
        }
        if !self.recovery.is_empty() {
            let _ = writeln!(output, "  recovery:");
            write_recovery_show(&mut output, &self.recovery);
        }
        if self.tcp_snd_nxt.is_some() || self.tcp_rcv_nxt.is_some() {
            let _ = writeln!(
                output,
                "  tcp state: snd_nxt={}, rcv_nxt={}",
                format_tcp_number(self.tcp_snd_nxt),
                format_tcp_number(self.tcp_rcv_nxt)
            );
        }
        let _ = writeln!(
            output,
            "  state trace: {} (final={}, bytes_sent={}, bytes_received={})",
            self.state_trace(),
            self.final_state().unwrap_or("none"),
            self.bytes_sent,
            self.bytes_received
        );
        let _ = writeln!(output, "  visited states:");
        if self.visited_states.is_empty() {
            let _ = writeln!(output, "    none");
        } else {
            for state in &self.visited_states {
                let _ = writeln!(output, "    - {state}");
            }
        }
        let _ = writeln!(output, "  transitions taken:");
        if self.transitions_taken.is_empty() {
            let _ = writeln!(output, "    none");
        } else {
            for transition in &self.transitions_taken {
                let _ = writeln!(output, "    - {transition}");
            }
        }
        let _ = writeln!(output, "  context: {}", self.context_snapshot);

        output
    }

    fn state_trace(&self) -> String {
        if self.visited_states.is_empty() {
            "none".to_string()
        } else {
            self.visited_states.join(" -> ")
        }
    }

    /// Return a compact JSON artifact for this run.
    ///
    /// Field names are stable for artifact consumers:
    /// `flow_name`, `role`, `dry_run`, `visited_states`, `sent_count`,
    /// `received_count`, `transitions_taken`, `iterations`, `elapsed_nanos`,
    /// `outcome`, optional `error`, optional `payload_protocol`, and
    /// `context_snapshot`.
    pub fn to_json(&self) -> String {
        let mut output = String::new();

        output.push('{');
        write_json_field(&mut output, "flow_name", &self.flow_name);
        output.push(',');
        write_json_field(&mut output, "role", &format!("{:?}", self.role));
        let _ = write!(output, ",\"dry_run\":{}", self.dry_run);
        output.push_str(",\"visited_states\":");
        write_json_string_array(&mut output, &self.visited_states);
        let _ = write!(
            output,
            ",\"sent_count\":{},\"received_count\":{}",
            self.sent_count, self.received_count
        );
        output.push_str(",\"transitions_taken\":");
        write_json_string_array(&mut output, &self.transitions_taken);
        let _ = write!(
            output,
            ",\"iterations\":{},\"elapsed_nanos\":{}",
            self.iterations,
            self.elapsed.as_nanos()
        );
        output.push(',');
        write_json_field(&mut output, "outcome", flow_outcome_name(&self.outcome));
        if let FlowOutcome::Error(error) = &self.outcome {
            output.push(',');
            write_json_field(&mut output, "error", error);
        }
        if let Some(protocol) = self.payload_protocol() {
            output.push(',');
            write_json_field(&mut output, "payload_protocol", protocol);
        }
        write_recovery_json(&mut output, &self.recovery);
        output.push(',');
        write_json_field(&mut output, "context_snapshot", &self.context_snapshot);
        output.push('}');

        output
    }
}

fn write_recovery_summary(output: &mut String, recovery: &RecoveryMetrics) {
    for (name, value) in recovery_fields(recovery) {
        if value != 0 {
            let _ = write!(output, ", {name}={value}");
        }
    }
}

fn write_recovery_show(output: &mut String, recovery: &RecoveryMetrics) {
    for (name, value) in recovery_fields(recovery) {
        if value != 0 {
            let _ = writeln!(output, "    {name}: {value}");
        }
    }
}

fn write_recovery_json(output: &mut String, recovery: &RecoveryMetrics) {
    for (name, value) in recovery_fields(recovery) {
        if value != 0 {
            let _ = write!(output, ",\"{name}\":{value}");
        }
    }
}

fn recovery_fields(recovery: &RecoveryMetrics) -> [(&'static str, u64); 5] {
    [
        ("timeout_events", recovery.timeout_events()),
        ("pto_firings", recovery.pto_firings()),
        ("packets_declared_lost", recovery.packets_declared_lost()),
        ("regenerated_transmits", recovery.regenerated_transmits()),
        ("exact_replay_transmits", recovery.exact_replay_transmits()),
    ]
}

fn format_tcp_number(value: Option<u32>) -> String {
    value
        .map(|value| format!("0x{value:08x}"))
        .unwrap_or_else(|| "n/a".to_string())
}

fn flow_outcome_name(outcome: &FlowOutcome) -> &'static str {
    match outcome {
        FlowOutcome::Completed => "Completed",
        FlowOutcome::TimedOut => "TimedOut",
        FlowOutcome::BoundExhausted => "BoundExhausted",
        FlowOutcome::Error(_) => "Error",
    }
}

fn write_json_field(output: &mut String, name: &str, value: &str) {
    write_json_string(output, name);
    output.push(':');
    write_json_string(output, value);
}

fn write_json_string_array(output: &mut String, values: &[String]) {
    output.push('[');
    for (index, value) in values.iter().enumerate() {
        if index > 0 {
            output.push(',');
        }
        write_json_string(output, value);
    }
    output.push(']');
}

fn write_json_string(output: &mut String, value: &str) {
    output.push('"');
    for ch in value.chars() {
        match ch {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            ch if ch.is_control() => {
                let _ = write!(output, "\\u{:04x}", ch as u32);
            }
            ch => output.push(ch),
        }
    }
    output.push('"');
}

#[cfg(test)]
mod tests {
    use std::time::Duration;

    use crate::{FlowOutcome, FlowReport, PacketContext, Role};

    #[test]
    fn report_summary_and_show_include_core_fields() {
        let report = FlowReport::new(
            "example-flow",
            Role::Initiator,
            true,
            vec!["Start".to_string(), "Done".to_string()],
            1,
            2,
            vec!["reply packet".to_string()],
            1,
            Duration::from_millis(7),
            FlowOutcome::Completed,
            "PacketContext keys=[transaction_id]",
        );

        assert_eq!(report.flow_name(), "example-flow");
        assert_eq!(report.role(), Role::Initiator);
        assert!(report.is_dry_run());
        assert_eq!(
            report.visited_states(),
            &["Start".to_string(), "Done".to_string()]
        );
        assert_eq!(report.sent_count(), 1);
        assert_eq!(report.received_count(), 2);
        assert_eq!(report.payload_protocol(), None);
        assert_eq!(report.bytes_sent(), 0);
        assert_eq!(report.bytes_received(), 0);
        assert_eq!(report.received_payload(), b"");
        assert_eq!(report.final_state(), Some("Done"));
        assert_eq!(report.transitions_taken(), &["reply packet".to_string()]);
        assert_eq!(report.iterations(), 1);
        assert_eq!(report.elapsed(), Duration::from_millis(7));
        assert_eq!(report.outcome(), &FlowOutcome::Completed);
        assert_eq!(
            report.context_snapshot(),
            "PacketContext keys=[transaction_id]"
        );
        assert!(report.summary().contains("example-flow"));
        assert!(report.summary().contains("dry_run=true"));
        assert!(report.summary().contains("state_trace=Start -> Done"));
        assert!(report.summary().contains("final_state=Done"));
        assert!(report.summary().contains("bytes_sent=0"));
        assert!(report.show().contains("dry-run: true"));
        assert!(report.show().contains("payload bytes: sent=0, received=0"));
        assert!(report
            .show()
            .contains("state trace: Start -> Done (final=Done"));
        assert!(report.show().contains("reply packet"));
    }

    #[test]
    fn report_reflects_tcp_payload_byte_counts() {
        let report = FlowReport::new(
            "payload-flow",
            Role::Initiator,
            true,
            vec!["Established".to_string()],
            1,
            1,
            vec!["tcp data".to_string()],
            1,
            Duration::from_millis(3),
            FlowOutcome::Completed,
            "PacketContext keys=[tcp_received_payload]",
        )
        .with_tcp_payload(12, b"peer-bytes".to_vec());

        assert_eq!(report.bytes_sent(), 12);
        assert_eq!(report.bytes_received(), 10);
        assert_eq!(report.received_payload(), b"peer-bytes");
        assert_eq!(report.payload_protocol(), Some("tcp"));
        assert_eq!(report.final_state(), Some("Established"));
        assert!(report.summary().contains("bytes_sent=12"));
        assert!(report.summary().contains("bytes_received=10"));
        assert!(report
            .show()
            .contains("payload bytes: sent=12, received=10"));
    }

    #[test]
    fn protocol_payload_metrics_preserve_tcp_compatibility() {
        let report = FlowReport::new(
            "tcp-payload-flow",
            Role::Initiator,
            true,
            vec!["Established".to_string()],
            1,
            1,
            vec!["tcp data".to_string()],
            1,
            Duration::from_millis(3),
            FlowOutcome::Completed,
            "PacketContext keys=[tcp_received_payload]",
        )
        .with_tcp_payload(12, b"peer-bytes".to_vec());

        assert_eq!(report.payload_protocol(), Some("tcp"));
        assert_eq!(report.bytes_sent(), 12);
        assert_eq!(report.bytes_received(), 10);
        assert_eq!(report.received_payload(), b"peer-bytes");
        assert!(report.summary().contains("bytes_sent=12"));
        assert!(report.summary().contains("bytes_received=10"));
        assert!(report.summary().contains("payload_protocol=tcp"));
        assert!(report
            .show()
            .contains("payload bytes: sent=12, received=10"));
        assert!(report.show().contains("payload protocol: tcp"));
        assert!(report.to_json().contains("\"payload_protocol\":\"tcp\""));
    }

    #[test]
    fn protocol_payload_metrics_label_quic() {
        let report = FlowReport::new(
            "quic-payload-flow",
            Role::Responder,
            true,
            vec!["Established".to_string()],
            2,
            2,
            vec!["quic stream data".to_string()],
            1,
            Duration::from_millis(4),
            FlowOutcome::Completed,
            "PacketContext keys=[quic::application_bytes_sent, quic::received_payload]",
        )
        .with_protocol_payload("quic", 14, b"opaque response".to_vec());

        assert_eq!(report.payload_protocol(), Some("quic"));
        assert_eq!(report.bytes_sent(), 14);
        assert_eq!(report.bytes_received(), 15);
        assert_eq!(report.received_payload(), b"opaque response");
        assert!(report.summary().contains("payload_protocol=quic"));
        assert!(report.show().contains("payload protocol: quic"));
        assert!(report.to_json().contains("\"payload_protocol\":\"quic\""));
    }

    #[test]
    fn report_show_includes_tcp_trace_counts_and_final_sequence_state() {
        let report = FlowReport::new(
            "tcp-client",
            Role::Initiator,
            true,
            vec![
                "SynSent".to_string(),
                "Established".to_string(),
                "FinWait1".to_string(),
                "FinWait2".to_string(),
                "Closed".to_string(),
            ],
            5,
            4,
            vec!["tcp SYN-ACK".to_string(), "tcp FIN".to_string()],
            5,
            Duration::from_millis(9),
            FlowOutcome::Completed,
            "PacketContext keys=[tcp_snd_nxt, tcp_rcv_nxt]",
        )
        .with_tcp_payload(17, b"server reply".to_vec())
        .with_tcp_state(Some(0x1020_3052), Some(0x5060_708d));

        let show = report.show();

        assert!(show.contains("role: Initiator"));
        assert!(
            show.contains("state trace: SynSent -> Established -> FinWait1 -> FinWait2 -> Closed")
        );
        assert!(show.contains("final state: Closed"));
        assert!(show.contains("payload bytes: sent=17, received=12"));
        assert!(show.contains("tcp state: snd_nxt=0x10203052, rcv_nxt=0x5060708d"));
    }

    #[test]
    fn report_json_contains_stable_core_fields() {
        let report = FlowReport::new(
            "json-flow",
            Role::Responder,
            true,
            vec!["Wait".to_string(), "Done".to_string()],
            2,
            3,
            vec!["matched packet".to_string()],
            1,
            Duration::from_micros(2),
            FlowOutcome::Completed,
            "PacketContext keys=[client_mac]",
        );

        let json = report.to_json();

        assert!(json.starts_with('{'));
        assert!(json.ends_with('}'));
        assert!(json.contains("\"flow_name\":\"json-flow\""));
        assert!(json.contains("\"role\":\"Responder\""));
        assert!(json.contains("\"outcome\":\"Completed\""));
        assert!(json.contains("\"visited_states\":[\"Wait\",\"Done\"]"));
        assert!(json.contains("\"elapsed_nanos\":2000"));
        assert!(json.contains("\"context_snapshot\":\"PacketContext keys=[client_mac]\""));
    }

    #[test]
    fn report_json_escapes_strings() {
        let report = FlowReport::new(
            "quoted \"flow\"",
            Role::Injector,
            false,
            vec!["Line\nOne".to_string()],
            0,
            0,
            vec!["slash\\match".to_string()],
            0,
            Duration::ZERO,
            FlowOutcome::Error("bad\tpacket".to_string()),
            "PacketContext keys=[]",
        );

        let json = report.to_json();

        assert!(json.contains("\"flow_name\":\"quoted \\\"flow\\\"\""));
        assert!(json.contains("\"visited_states\":[\"Line\\nOne\"]"));
        assert!(json.contains("\"transitions_taken\":[\"slash\\\\match\"]"));
        assert!(json.contains("\"outcome\":\"Error\""));
        assert!(json.contains("\"error\":\"bad\\tpacket\""));
    }

    #[test]
    fn recovery_metrics_are_inspectable() {
        let empty_report = FlowReport::new(
            "empty-recovery",
            Role::Initiator,
            true,
            Vec::new(),
            0,
            0,
            Vec::new(),
            0,
            Duration::ZERO,
            FlowOutcome::Completed,
            "PacketContext keys=[]",
        );
        assert_eq!(empty_report.recovery_metrics().timeout_events(), 0);
        assert!(!empty_report.summary().contains("timeout_events"));
        assert!(!empty_report.show().contains("recovery:"));
        assert!(!empty_report.to_json().contains("timeout_events"));

        let mut context = PacketContext::new();
        context.add_timeout_events(2);
        context.add_pto_firings(3);
        context.add_packets_declared_lost(5);
        context.add_regenerated_transmits(7);
        context.add_exact_replay_transmits(11);

        let report = FlowReport::new(
            "recovery-flow",
            Role::Responder,
            true,
            vec!["Recovering".to_string()],
            1,
            1,
            Vec::new(),
            1,
            Duration::from_millis(1),
            FlowOutcome::Completed,
            context.summary(),
        )
        .with_recovery_metrics(context.recovery_metrics());

        let metrics = report.recovery_metrics();
        assert_eq!(metrics.timeout_events(), 2);
        assert_eq!(metrics.pto_firings(), 3);
        assert_eq!(metrics.packets_declared_lost(), 5);
        assert_eq!(metrics.regenerated_transmits(), 7);
        assert_eq!(metrics.exact_replay_transmits(), 11);
        assert!(report.summary().contains("timeout_events=2"));
        assert!(report.summary().contains("regenerated_transmits=7"));
        assert!(report.show().contains("    pto_firings: 3"));
        assert!(report.show().contains("    packets_declared_lost: 5"));
        assert!(report.to_json().contains(
            "\"timeout_events\":2,\"pto_firings\":3,\"packets_declared_lost\":5,\"regenerated_transmits\":7,\"exact_replay_transmits\":11"
        ));
    }
}
