[package]
name = "crafter-flow"
version = "0.0.0"
edition = "2021"
publish = false

[features]
default = []
quic-endpoint = ["dep:bytes", "dep:quinn-proto", "dep:rustls"]

[dependencies]
bytes = { version = "1", optional = true }
crafter = { path = "../../crafter" }
quinn-proto = { version = "=0.11.16", default-features = false, features = ["qlog", "rustls-ring"], optional = true }
rustls = { version = "=0.23.5", default-features = false, features = ["ring", "std"], optional = true }

[[example]]
name = "quic_client_flow"
path = "examples/quic_client_flow.rs"
required-features = ["quic-endpoint"]

[[example]]
name = "quic_server_flow"
path = "examples/quic_server_flow.rs"
required-features = ["quic-endpoint"]
