"""Scapy raw packet materialization for oracle packet plans."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from ...model import EncodedVector, JSONObject, PacketPlan
from .bootstrap import import_scapy


BACKEND_NAME = "scapy"

_ETHERTYPES: dict[str, int] = {
    "arp": 0x0806,
    "experimental": 0x9000,
    "ipv4": 0x0800,
    "ip": 0x0800,
    "ipv6": 0x86DD,
    "unknown": 0x9000,
    "vlan": 0x8100,
}
_IP_PROTOCOLS: dict[str, int] = {
    "icmp": 1,
    "tcp": 6,
    "unknown": 253,
    "udp": 17,
}
_IPV6_NEXT_HEADERS: dict[str, int] = {
    "fragment": 44,
    "routing": 43,
    "icmpv6": 58,
    "payload": 253,
    "raw": 253,
    "tcp": 6,
    "unknown": 253,
    "udp": 17,
}
_ROOT_BY_LAYER: dict[str, str] = {
    "ethernet": "link:ethernet",
    "payload": "link:raw",
    "raw": "link:raw",
    "ipv4": "l3:ipv4",
    "ip": "l3:ipv4",
    "ipv6": "l3:ipv6",
}
_DECODER_BY_LAYER: dict[str, str] = {
    "ethernet": "Ether",
    "payload": "Raw",
    "raw": "Raw",
    "ipv4": "IP",
    "ip": "IP",
    "ipv6": "IPv6",
}
_SCAPY_LAYER_BY_LAYER: dict[str, str] = {
    "arp": "ARP",
    "dns": "DNS",
    "ethernet": "Ether",
    "icmp": "ICMP",
    "icmpv6": "ICMPv6EchoRequest",
    "ipv6_fragment": "IPv6ExtHdrFragment",
    "ipv6_routing": "IPv6ExtHdrRouting",
    "ipv4": "IP",
    "ipv6": "IPv6",
    "payload": "Raw",
    "raw": "Raw",
    "tcp": "TCP",
    "udp": "UDP",
    "vlan": "Dot1Q",
}


def encode_packet_plan(plan: PacketPlan) -> EncodedVector:
    """Materialize one backend-neutral packet plan as Scapy-generated bytes."""

    scapy = import_scapy()
    scapy_all = scapy["all"]
    scapy_version = _string(scapy["version"], "unknown")
    raw = scapy_all.raw

    stack = _canonical_stack(plan.stack)
    if not stack:
        raise ValueError("packet plan stack must contain at least one layer")

    packet = None
    for index, layer in enumerate(stack):
        piece = _build_layer(plan, stack, index, scapy_all)
        packet = piece if packet is None else packet / piece

    if packet is None:
        raise ValueError("packet plan did not produce a packet")

    raw_bytes = bytes(raw(packet))
    return EncodedVector.from_bytes(
        plan=plan,
        backend=BACKEND_NAME,
        raw=raw_bytes,
        root=_root_decoder(stack),
        decoder=_scapy_decoder(stack),
        metadata={
            "backend": BACKEND_NAME,
            "scapy_version": scapy_version,
            "stack_tags": list(plan.feature_tags),
            "strict_bytes": plan.strict_bytes,
            "scapy_stack": [_scapy_layer_name(layer) for layer in stack],
            "length": len(raw_bytes),
        },
    )


def encode_packet_plans(plans: list[PacketPlan]) -> list[EncodedVector]:
    """Materialize packet plans in order."""

    return [encode_packet_plan(plan) for plan in plans]


def _build_layer(plan: PacketPlan, stack: list[str], index: int, scapy_all: Any) -> Any:
    layer = stack[index]
    fields = plan.fields

    if layer == "payload" or layer == "raw":
        return scapy_all.Raw(load=_payload_bytes(fields))
    if layer == "ethernet":
        return _ethernet(plan, stack, index, scapy_all)
    if layer == "vlan":
        return _vlan(plan, stack, index, scapy_all)
    if layer == "arp":
        return _arp(fields, scapy_all)
    if layer == "ipv4":
        return _ipv4(fields, stack, index, scapy_all)
    if layer == "ipv6":
        return _ipv6(fields, stack, index, scapy_all)
    if layer == "ipv6_fragment":
        return _ipv6_fragment(fields, stack, index, scapy_all)
    if layer == "ipv6_routing":
        return _ipv6_routing(fields, stack, index, scapy_all)
    if layer == "icmp":
        return _icmp(fields, scapy_all)
    if layer == "icmpv6":
        return _icmpv6(fields, stack, scapy_all)
    if layer == "udp":
        return _udp(fields, stack, scapy_all)
    if layer == "tcp":
        return _tcp(fields, scapy_all)
    if layer == "dns":
        return _dns(fields, scapy_all)
    if layer == "dhcp":
        return _dhcp(fields, scapy_all)

    raise ValueError(f"unsupported Scapy materialization layer: {layer}")


def _ethernet(plan: PacketPlan, stack: list[str], index: int, scapy_all: Any) -> Any:
    fields = _layer_fields(plan.fields, "ethernet")
    kwargs: dict[str, Any] = {
        "src": _text(fields.get("src"), "00:00:5e:00:53:01"),
        "dst": _text(fields.get("dst"), _default_ethernet_dst(stack)),
    }
    ethertype = fields.get("type", fields.get("ethertype"))
    if ethertype is not None:
        kwargs["type"] = _ethertype_value(ethertype)
    else:
        kwargs["type"] = _ethertype_for_next_layer(stack, index)
    return scapy_all.Ether(**kwargs)


def _vlan(plan: PacketPlan, stack: list[str], index: int, scapy_all: Any) -> Any:
    fields = _layer_fields(plan.fields, "vlan")
    kwargs: dict[str, Any] = {
        "prio": _int(fields.get("priority", fields.get("prio")), 0),
        "vlan": _int(fields.get("id", fields.get("vlan", fields.get("vlan_id"))), 1),
        "type": _ethertype_for_next_layer(stack, index),
    }
    ethertype = fields.get("ethertype", fields.get("type"))
    if ethertype is not None:
        kwargs["type"] = _ethertype_value(ethertype)
    if "dei" in fields or "drop_eligible" in fields:
        kwargs["dei"] = _int(fields.get("dei", fields.get("drop_eligible")), 0)
    return scapy_all.Dot1Q(**kwargs)


def _arp(fields: Mapping[str, JSONObject], scapy_all: Any) -> Any:
    arp_fields = _layer_fields(fields, "arp")
    ethernet_fields = _layer_fields(fields, "ethernet")
    op = arp_fields.get("op", arp_fields.get("operation", arp_fields.get("opcode")))
    kwargs: dict[str, Any] = {
        "op": _arp_op(op),
        "hwsrc": _text(
            arp_fields.get("hwsrc", arp_fields.get("sender_hardware_address")),
            _text(ethernet_fields.get("src"), "00:00:5e:00:53:01"),
        ),
        "psrc": _text(
            arp_fields.get(
                "psrc",
                arp_fields.get("sender_ip", arp_fields.get("sender_protocol_address")),
            ),
            "192.0.2.10",
        ),
        "hwdst": _text(
            arp_fields.get("hwdst", arp_fields.get("target_hardware_address")),
            _text(ethernet_fields.get("dst"), "00:00:00:00:00:00"),
        ),
        "pdst": _text(
            arp_fields.get(
                "pdst",
                arp_fields.get("target_ip", arp_fields.get("target_protocol_address")),
            ),
            "192.0.2.1",
        ),
    }
    if "hardware_type" in arp_fields or "hwtype" in arp_fields:
        kwargs["hwtype"] = _int(arp_fields.get("hardware_type", arp_fields.get("hwtype")), 1)
    if "protocol_type" in arp_fields or "ptype" in arp_fields:
        kwargs["ptype"] = _ethertype_value(arp_fields.get("protocol_type", arp_fields.get("ptype")))
    return scapy_all.ARP(**kwargs)


def _ipv4(fields: Mapping[str, JSONObject], stack: list[str], index: int, scapy_all: Any) -> Any:
    ipv4_fields = _layer_fields(fields, "ipv4")
    kwargs: dict[str, Any] = {
        "src": _text(ipv4_fields.get("src"), "192.0.2.10"),
        "dst": _text(ipv4_fields.get("dst"), "198.51.100.20"),
        "id": _int(ipv4_fields.get("id", ipv4_fields.get("identification")), 0x1234),
        "ttl": _int(ipv4_fields.get("ttl"), 64),
    }
    if "tos" in ipv4_fields:
        kwargs["tos"] = _int(ipv4_fields.get("tos"), 0)
    if "flags" in ipv4_fields:
        kwargs["flags"] = _ipv4_flags(ipv4_fields["flags"])
    elif _next_payload_layer(stack, index) == "icmp":
        kwargs["flags"] = "DF"
    if "fragment_offset" in ipv4_fields or "frag" in ipv4_fields:
        kwargs["frag"] = _int(ipv4_fields.get("fragment_offset", ipv4_fields.get("frag")), 0)
    next_layer = _next_payload_layer(stack, index)
    if next_layer not in {"icmp", "tcp", "udp"}:
        protocol = ipv4_fields.get("protocol", ipv4_fields.get("proto"))
        if protocol is not None:
            kwargs["proto"] = _protocol_value(protocol, _IP_PROTOCOLS)
    return scapy_all.IP(**kwargs)


def _ipv6(fields: Mapping[str, JSONObject], stack: list[str], index: int, scapy_all: Any) -> Any:
    ipv6_fields = _layer_fields(fields, "ipv6")
    kwargs: dict[str, Any] = {
        "src": _text(ipv6_fields.get("src"), "2001:db8:1::10"),
        "dst": _text(ipv6_fields.get("dst"), "2001:db8:2::20"),
        "hlim": _int(ipv6_fields.get("hop_limit", ipv6_fields.get("hlim")), 64),
    }
    if "traffic_class" in ipv6_fields or "tc" in ipv6_fields:
        kwargs["tc"] = _int(ipv6_fields.get("traffic_class", ipv6_fields.get("tc")), 0)
    if "flow_label" in ipv6_fields or "fl" in ipv6_fields:
        kwargs["fl"] = _int(ipv6_fields.get("flow_label", ipv6_fields.get("fl")), 0)
    next_layer = _next_payload_layer(stack, index)
    if next_layer not in {"icmpv6", "tcp", "udp"}:
        next_header = ipv6_fields.get("next_header", ipv6_fields.get("nh"))
        if next_header is not None:
            kwargs["nh"] = _protocol_value(next_header, _IPV6_NEXT_HEADERS)
    return scapy_all.IPv6(**kwargs)


def _ipv6_fragment(
    fields: Mapping[str, JSONObject],
    stack: list[str],
    index: int,
    scapy_all: Any,
) -> Any:
    fragment_fields = _layer_fields(fields, "ipv6_fragment")
    kwargs: dict[str, Any] = {
        "nh": _protocol_value(
            fragment_fields.get("next_header", fragment_fields.get("nh", _next_payload_layer(stack, index))),
            _IPV6_NEXT_HEADERS,
        ),
        "id": _int(fragment_fields.get("identification", fragment_fields.get("id")), 0x12345678),
        "offset": _int(fragment_fields.get("fragment_offset", fragment_fields.get("offset")), 0),
        "m": _int(fragment_fields.get("more_fragments", fragment_fields.get("m")), 0),
    }
    if "reserved" in fragment_fields:
        kwargs["res1"] = _int(fragment_fields.get("reserved"), 0)
    return scapy_all.IPv6ExtHdrFragment(**kwargs)


def _ipv6_routing(
    fields: Mapping[str, JSONObject],
    stack: list[str],
    index: int,
    scapy_all: Any,
) -> Any:
    routing_fields = _layer_fields(fields, "ipv6_routing")
    kwargs: dict[str, Any] = {
        "nh": _protocol_value(
            routing_fields.get("next_header", routing_fields.get("nh", _next_payload_layer(stack, index))),
            _IPV6_NEXT_HEADERS,
        ),
        "type": _int(routing_fields.get("type", routing_fields.get("routing_type")), 0),
        "segleft": _int(routing_fields.get("segments_left", routing_fields.get("segleft")), 0),
    }
    addresses = routing_fields.get("addresses")
    if isinstance(addresses, list):
        kwargs["addresses"] = addresses
    return scapy_all.IPv6ExtHdrRouting(**kwargs)


def _icmp(fields: Mapping[str, JSONObject], scapy_all: Any) -> Any:
    icmp_fields = _layer_fields(fields, "icmp")
    return scapy_all.ICMP(
        type=_icmp_type(icmp_fields.get("type", "echo-request")),
        code=_int(icmp_fields.get("code"), 0),
        id=_int(icmp_fields.get("id", icmp_fields.get("identifier")), 0x4242),
        seq=_int(icmp_fields.get("seq", icmp_fields.get("sequence")), 1),
    )


def _icmpv6(fields: Mapping[str, JSONObject], stack: list[str], scapy_all: Any) -> Any:
    icmpv6_fields = _layer_fields(fields, "icmpv6")
    kwargs: dict[str, Any] = {
        "id": _int(icmpv6_fields.get("id", icmpv6_fields.get("identifier")), 0x4242),
        "seq": _int(icmpv6_fields.get("seq", icmpv6_fields.get("sequence")), 1),
    }
    if "payload" not in stack:
        payload = _payload_bytes(fields)
        if payload:
            kwargs["data"] = payload
    icmp_type = _icmp_type(icmpv6_fields.get("type", "echo_request"))
    if icmp_type == "echo-reply":
        return scapy_all.ICMPv6EchoReply(**kwargs)
    return scapy_all.ICMPv6EchoRequest(**kwargs)


def _udp(fields: Mapping[str, JSONObject], stack: list[str], scapy_all: Any) -> Any:
    udp_fields = _layer_fields(fields, "udp")
    dns_fields = _layer_fields(fields, "dns")
    default_dst = 53 if "dns" in stack else 33434
    kwargs: dict[str, Any] = {
        "sport": _int(udp_fields.get("src_port", udp_fields.get("sport")), 53000),
        "dport": _int(udp_fields.get("dst_port", udp_fields.get("dport")), default_dst),
    }
    if dns_fields and "dst_port" not in udp_fields and "dport" not in udp_fields:
        kwargs["dport"] = 53
    if "checksum" in udp_fields or "chksum" in udp_fields:
        kwargs["chksum"] = _int(udp_fields.get("checksum", udp_fields.get("chksum")), 0)
    return scapy_all.UDP(**kwargs)


def _tcp(fields: Mapping[str, JSONObject], scapy_all: Any) -> Any:
    tcp_fields = _layer_fields(fields, "tcp")
    kwargs: dict[str, Any] = {
        "sport": _int(tcp_fields.get("src_port", tcp_fields.get("sport")), 40000),
        "dport": _int(tcp_fields.get("dst_port", tcp_fields.get("dport")), 80),
        "flags": _tcp_flags(tcp_fields.get("flags", "S")),
        "seq": _int(tcp_fields.get("seq", tcp_fields.get("sequence")), 0x01020304),
        "window": _int(tcp_fields.get("window"), 64240),
    }
    if "ack" in tcp_fields or "acknowledgement" in tcp_fields:
        kwargs["ack"] = _int(tcp_fields.get("ack", tcp_fields.get("acknowledgement")), 0)
    if "reserved" in tcp_fields:
        kwargs["reserved"] = _int(tcp_fields.get("reserved"), 0)
    if "urgent_pointer" in tcp_fields or "urgptr" in tcp_fields:
        kwargs["urgptr"] = _int(tcp_fields.get("urgent_pointer", tcp_fields.get("urgptr")), 0)
    if "options" in tcp_fields:
        kwargs["options"] = tcp_fields["options"]
    return scapy_all.TCP(**kwargs)


def _dns(fields: Mapping[str, JSONObject], scapy_all: Any) -> Any:
    dns_fields = _layer_fields(fields, "dns")
    question = _first_question(dns_fields)
    qname = _text(
        dns_fields.get("qname", dns_fields.get("query", question.get("qname"))),
        "example.com.",
    )
    if not qname.endswith("."):
        qname = f"{qname}."
    return scapy_all.DNS(
        id=_int(dns_fields.get("id", dns_fields.get("transaction_id")), 0xBEEF),
        rd=_int(dns_fields.get("rd"), 1),
        qd=scapy_all.DNSQR(
            qname=qname,
            qtype=_text(dns_fields.get("qtype", question.get("qtype")), "A"),
        ),
    )


def _dhcp(fields: Mapping[str, JSONObject], scapy_all: Any) -> Any:
    dhcp_fields = _layer_fields(fields, "dhcp")
    bootp = scapy_all.BOOTP(
        op=_dhcp_op(dhcp_fields.get("op")),
        htype=_int(dhcp_fields.get("hardware_type", dhcp_fields.get("htype")), 1),
        hlen=_int(dhcp_fields.get("hardware_length", dhcp_fields.get("hlen")), 6),
        xid=_int(dhcp_fields.get("transaction_id", dhcp_fields.get("xid")), 0x12345678),
        flags=_dhcp_flags(dhcp_fields.get("flags")),
        ciaddr=_text(dhcp_fields.get("client_ip", dhcp_fields.get("ciaddr")), "0.0.0.0"),
        yiaddr=_text(dhcp_fields.get("your_ip", dhcp_fields.get("yiaddr")), "0.0.0.0"),
        chaddr=_dhcp_chaddr(dhcp_fields.get("client_hardware_address", dhcp_fields.get("chaddr"))),
    )
    return bootp / scapy_all.DHCP(options=_dhcp_options(dhcp_fields.get("options")))


def _canonical_stack(stack: list[str]) -> list[str]:
    aliases = {
        "dot1q": "vlan",
        "ether": "ethernet",
        "ip": "ipv4",
        "raw": "payload",
    }
    return [aliases.get(layer.lower(), layer.lower()) for layer in stack]


def _layer_fields(fields: Mapping[str, JSONObject], layer: str) -> JSONObject:
    value = fields.get(layer)
    if value is None and layer == "ipv4":
        value = fields.get("ip")
    if value is None and layer == "payload":
        value = fields.get("raw")
    if value is None:
        return {}
    if not isinstance(value, Mapping):
        raise ValueError(f"{layer} fields must be an object")
    return dict(value)


def _payload_bytes(fields: Mapping[str, JSONObject]) -> bytes:
    payload = _layer_fields(fields, "payload")
    if "hex" in payload:
        return bytes.fromhex(_text(payload.get("hex"), ""))
    if "bytes_hex" in payload:
        return bytes.fromhex(_text(payload.get("bytes_hex"), ""))
    if "text" in payload:
        return _text(payload.get("text"), "").encode("utf-8")
    if "value" in payload:
        return _text(payload.get("value"), "").encode("utf-8")
    length = _int(payload.get("length"), 0)
    return bytes(length)


def _default_ethernet_dst(stack: list[str]) -> str:
    if "arp" in stack:
        return "ff:ff:ff:ff:ff:ff"
    return "00:00:5e:00:53:02"


def _ethertype_for_next_layer(stack: list[str], index: int) -> int:
    next_layer = _next_payload_layer(stack, index)
    return _ETHERTYPES.get(next_layer, 0x9000)


def _next_payload_layer(stack: list[str], index: int) -> str:
    for layer in stack[index + 1 :]:
        if layer != "payload":
            return layer
    return "payload"


def _ethertype_value(value: object) -> int:
    if isinstance(value, str):
        lowered = value.lower()
        if lowered in _ETHERTYPES:
            return _ETHERTYPES[lowered]
        return int(lowered, 0)
    return _int(value, 0x9000)


def _protocol_value(value: object, mapping: Mapping[str, int]) -> int:
    if isinstance(value, str):
        lowered = value.lower()
        if lowered in mapping:
            return mapping[lowered]
        return int(lowered, 0)
    return _int(value, 0)


def _arp_op(value: object) -> int | str:
    if value is None:
        return 1
    if isinstance(value, str):
        lowered = value.lower()
        if lowered in {"who-has", "request"}:
            return 1
        if lowered in {"is-at", "reply"}:
            return 2
        return lowered
    return _int(value, 1)


def _ipv4_flags(value: object) -> object:
    if isinstance(value, str):
        lowered = value.lower().replace("_", "-")
        if lowered in {"none", "0"}:
            return 0
        if lowered in {"df", "dont-fragment"}:
            return "DF"
        if lowered in {"mf", "more-fragments"}:
            return "MF"
    return value


def _icmp_type(value: object) -> object:
    if isinstance(value, str):
        lowered = value.lower().replace("_", "-")
        aliases = {
            "destination-unreachable": "dest-unreach",
            "echo-reply": "echo-reply",
            "echo-request": "echo-request",
            "parameter-problem": "parameter-problem",
            "time-exceeded": "time-exceeded",
        }
        return aliases.get(lowered, lowered)
    return value


def _tcp_flags(value: object) -> object:
    flag_names = {
        "fin": "F",
        "syn": "S",
        "rst": "R",
        "psh": "P",
        "ack": "A",
        "urg": "U",
        "ece": "E",
        "cwr": "C",
    }
    if isinstance(value, str):
        lowered = value.lower()
        if lowered == "all":
            return 0x1FF
        return flag_names.get(lowered, value)
    if isinstance(value, list):
        output = ""
        for item in value:
            if not isinstance(item, str):
                return value
            lowered = item.lower()
            if lowered == "all":
                return 0x1FF
            output += flag_names.get(lowered, item)
        return output
    return value


def _dhcp_op(value: object) -> int:
    if isinstance(value, str):
        lowered = value.lower().replace("_", "-")
        if lowered in {"bootrequest", "request"}:
            return 1
        if lowered in {"bootreply", "reply"}:
            return 2
    return _int(value, 1)


def _dhcp_flags(value: object) -> int:
    if isinstance(value, str):
        lowered = value.lower().replace("_", "-")
        if lowered in {"broadcast", "b"}:
            return 0x8000
        if lowered in {"none", "0"}:
            return 0
    return _int(value, 0)


def _dhcp_chaddr(value: object) -> bytes:
    mac = _text(value, "00:00:5e:00:53:01")
    raw = bytes.fromhex(mac.replace(":", ""))
    return raw.ljust(16, b"\x00")


def _dhcp_options(value: object) -> list[object]:
    if not isinstance(value, list):
        return [("message-type", "discover"), "end"]
    options: list[object] = []
    for item in value:
        if isinstance(item, str):
            if item == "end":
                options.append("end")
                continue
            if "=" in item:
                name, raw_value = item.split("=", 1)
                options.append((name, raw_value))
                continue
        options.append(item)
    if not options or options[-1] != "end":
        options.append("end")
    return options


def _first_question(dns_fields: Mapping[str, object]) -> JSONObject:
    questions = dns_fields.get("questions")
    if isinstance(questions, list) and questions:
        first = questions[0]
        if isinstance(first, Mapping):
            return dict(first)  # type: ignore[arg-type, return-value]
        if isinstance(first, str):
            return {"qname": first}
    return {}


def _root_decoder(stack: list[str]) -> str:
    return _ROOT_BY_LAYER.get(stack[0], stack[0])


def _scapy_decoder(stack: list[str]) -> str:
    return _DECODER_BY_LAYER.get(stack[0], _scapy_layer_name(stack[0]))


def _scapy_layer_name(layer: str) -> str:
    return _SCAPY_LAYER_BY_LAYER.get(layer, layer)


def _int(value: object, default: int) -> int:
    if value is None:
        return default
    if isinstance(value, bool):
        return int(value)
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        return int(value, 0)
    raise ValueError(f"expected integer-compatible value, got {value!r}")


def _text(value: object, default: str) -> str:
    if value is None:
        return default
    if isinstance(value, str):
        return value
    return str(value)


def _string(value: object, default: str) -> str:
    if isinstance(value, str):
        return value
    return default
