//! Public crate for packet-level network interaction.
//!
//! `crafter` is the only public crate. It exposes a self-contained API for
//! examples, generated tools, and agent-directed packet workflows:
//!
//! - packet construction, decode, checksums, and protocol layers
//! - pcap read/write and sniffing helpers
//! - interface, send, send/receive, batch, and address helpers
//!
//! Public modules are organized as `crafter::core`, `crafter::pcap`,
//! `crafter::net`, and `crafter::prelude`. Most examples should start with
//! `use crafter::prelude::*;`.
//!
//! Local examples use dry-run send plans or offline pcaps unless live behavior
//! is explicitly requested.
//!
//! ```rust
//! use crafter::prelude::*;
//! use std::net::Ipv4Addr;
//!
//! # fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
//! let packet = Ipv4::new()
//!     .src(Ipv4Addr::new(192, 0, 2, 10))
//!     .dst(Ipv4Addr::new(198, 51, 100, 20))
//!     / Icmp::echo_request().id(0x4242).seq(1)
//!     / Raw::from("hello");
//!
//! let compiled = packet.compile()?;
//! println!("{}", packet.summary());
//! println!("{}", compiled.hexdump());
//! # Ok(())
//! # }
//! ```

#![forbid(unsafe_code)]

#[cfg(test)]
#[macro_use]
#[path = "../tests/support/mod.rs"]
mod test_support;

pub mod checksum;
pub mod endian;
pub mod error;
pub mod field;
pub mod mac;
pub mod packet;
pub mod protocols;
pub mod registry;

pub mod net;
pub mod pcap;

pub use error::{CrafterError, Result};
pub use field::{Field, FieldState};
pub use mac::MacAddr;
pub use packet::{
    hexdump, CompiledPacket, IntoPacket, Layer, LayerContext, LinkType, NetworkLayer, Packet, Raw,
    TransportChecksumContext,
};
pub use protocols::{
    arp_hardware_type_label, arp_protocol_type_label, decode_dns_name, decode_dns_name_typed,
    decode_tftp_server_addresses, dns_type_name, edns_option_code_name, option_meta, option_name,
    option_status, scan_dhcp_option_segments, svcb_param_key_name, typed_option_value,
    udp_option_kind_class, udp_option_kind_is_unsafe, udp_option_kind_is_unsupported, Arp,
    ArpOperation, ClientNetworkDeviceInterface, ClientSystemArchitecture, Dhcp, DhcpAuthAlgorithm,
    DhcpAuthProtocol, DhcpAuthentication, DhcpClasslessRoute, DhcpClientIdentifier, DhcpClientUuid,
    DhcpDataSource, DhcpForcerenewNonceCapable, DhcpMalformed, DhcpMessageType, DhcpOption,
    DhcpOptionArea, DhcpOptionCode, DhcpOptionFormat, DhcpOptionKind, DhcpOptionMeta,
    DhcpOptionSegment, DhcpOptionStatus, DhcpOptionValue, DhcpRelayAgentInfo, DhcpRelaySuboption,
    DhcpRelayVendorSpecific, DhcpReplayDetectionMethod, DhcpState, DhcpStaticRoute, DhcpStatusCode,
    DhcpStatusCodeOption, DhcpUserClass, DhcpVendorClassData, DhcpVendorIdentifyingOption,
    DhcpVendorSuboption, DhcpVssInfo, Dns, DnsName, DnsQuestion, DnsRecord, DnsRecordData,
    DnsTypeBitmaps, Dot1Q, EdnsOption, Ethernet, Icmp, IcmpAddressMask, IcmpExtension,
    IcmpExtensionInterfaceInfo, IcmpExtensionMpls, IcmpExtensionObject, IcmpInterfaceIpAddress,
    IcmpKind, IcmpLayer, IcmpQuotedIpv4, IcmpRouterAdvertisementEntry, IcmpTimestamp, Icmpv6,
    IpProtocol, Ipv4,
    Ipv4Option, Ipv4OptionIter, Ipv4RouteOptionKind, Ipv6, Ipv6FragmentHeader,
    Ipv6MobileRoutingHeader, Ipv6RoutingHeader, Ipv6SegmentRoutingHeader, LinuxSll,
    NullByteOrder, NullLoopback, OptionOverload, SipServers, SvcParam, SvcParams, Tcp,
    TcpExtendedDataOffset, TcpOption, TcpOptionIter, TcpSackBlock, Udp, UdpChecksumStatus,
    UdpOption, UdpOptionIter, UdpOptionKindClass, UdpOptionStatus, UdpOptions, Vlan, ARP_HRD_ATM,
    ARP_HRD_ETHERNET, ARP_HRD_FIBRE_CHANNEL, ARP_HRD_IEEE_802,
    ARP_HRD_INFINIBAND, ARP_HRD_MAPOS, ARP_OP_ARP_NAK, ARP_OP_DRARP_ERROR, ARP_OP_DRARP_REPLY,
    ARP_OP_DRARP_REQUEST, ARP_OP_EXP1, ARP_OP_EXP2, ARP_OP_INARP_REPLY, ARP_OP_INARP_REQUEST,
    ARP_OP_MAPOS_UNARP, ARP_OP_RARP_REPLY, ARP_OP_RARP_REQUEST, ARP_OP_REPLY, ARP_OP_REQUEST,
    ARP_OP_RESERVED, ARP_OP_RESERVED_MAX, ARP_PRO_IPV4, BOOTP_REPLY, BOOTP_REQUEST, DHCP_ACK,
    DHCP_AUTH_ALGORITHM_HMAC_MD5, DHCP_AUTH_HEADER_LEN, DHCP_AUTH_PROTOCOL_CONFIGURATION_TOKEN,
    DHCP_AUTH_PROTOCOL_DELAYED, DHCP_AUTH_PROTOCOL_RECONFIGURE_KEY,
    DHCP_AUTH_RDM_MONOTONIC_COUNTER, DHCP_AUTH_REPLAY_DETECTION_LEN, DHCP_CLIENT_PORT,
    DHCP_DECLINE, DHCP_DISCOVER, DHCP_FORCERENEW_NONCE_TYPE_HMAC_MD5,
    DHCP_FORCERENEW_NONCE_TYPE_NONCE, DHCP_HTYPE_ETHERNET, DHCP_INFORM, DHCP_MAGIC_COOKIE,
    DHCP_MAGIC_COOKIE_LEN, DHCP_MIN_LEN, DHCP_NAK, DHCP_OFFER, DHCP_OPTION_AUTHENTICATION,
    DHCP_OPTION_BROADCAST_ADDRESS, DHCP_OPTION_CLIENT_IDENTIFIER, DHCP_OPTION_DOMAIN_NAME,
    DHCP_OPTION_DOMAIN_NAME_SERVER, DHCP_OPTION_END, DHCP_OPTION_FORCERENEW_NONCE_CAPABLE,
    DHCP_OPTION_HOST_NAME, DHCP_OPTION_IP_ADDRESS_LEASE_TIME, DHCP_OPTION_MESSAGE_TYPE,
    DHCP_OPTION_OVERLOAD, DHCP_OPTION_PAD, DHCP_OPTION_PARAMETER_REQUEST_LIST,
    DHCP_OPTION_PRIVATE_USE_END, DHCP_OPTION_PRIVATE_USE_START, DHCP_OPTION_REBINDING_TIME,
    DHCP_OPTION_RELAY_AGENT_INFORMATION, DHCP_OPTION_RENEWAL_TIME,
    DHCP_OPTION_REQUESTED_IP_ADDRESS, DHCP_OPTION_ROUTER, DHCP_OPTION_SERVER_IDENTIFIER,
    DHCP_OPTION_SUBNET_MASK, DHCP_OVERLOAD_BOTH, DHCP_OVERLOAD_FILE, DHCP_OVERLOAD_SNAME,
    DHCP_RELAY_FLAG_UNICAST, DHCP_RELAY_SUBOPTION_ACCESS_NETWORK_NAME,
    DHCP_RELAY_SUBOPTION_ACCESS_POINT_BSSID, DHCP_RELAY_SUBOPTION_ACCESS_POINT_NAME,
    DHCP_RELAY_SUBOPTION_ACCESS_TECHNOLOGY_TYPE, DHCP_RELAY_SUBOPTION_AUTHENTICATION,
    DHCP_RELAY_SUBOPTION_CIRCUIT_ID, DHCP_RELAY_SUBOPTION_DOCSIS_DEVICE_CLASS,
    DHCP_RELAY_SUBOPTION_LINK_SELECTION, DHCP_RELAY_SUBOPTION_OPERATOR_IDENTIFIER,
    DHCP_RELAY_SUBOPTION_OPERATOR_REALM, DHCP_RELAY_SUBOPTION_RADIUS_ATTRIBUTES,
    DHCP_RELAY_SUBOPTION_RELAY_AGENT_ID, DHCP_RELAY_SUBOPTION_RELAY_FLAGS,
    DHCP_RELAY_SUBOPTION_RELAY_SOURCE_PORT, DHCP_RELAY_SUBOPTION_REMOTE_ID,
    DHCP_RELAY_SUBOPTION_SERVER_ID_OVERRIDE, DHCP_RELAY_SUBOPTION_SUBSCRIBER_ID,
    DHCP_RELAY_SUBOPTION_VENDOR_SPECIFIC, DHCP_RELAY_SUBOPTION_VSS,
    DHCP_RELAY_SUBOPTION_VSS_CONTROL, DHCP_RELEASE, DHCP_REQUEST, DHCP_SERVER_PORT,
    DHCP_VSS_TYPE_GLOBAL_DEFAULT, DHCP_VSS_TYPE_NVT_ASCII, DHCP_VSS_TYPE_VPN_ID, DNS_CLASS_ANY,
    DNS_CLASS_CH, DNS_CLASS_HS, DNS_CLASS_IN, DNS_CLASS_NONE, DNS_EDNS_DEFAULT_UDP_PAYLOAD_SIZE,
    DNS_EDNS_FLAG_DO, DNS_EDNS_OPTION_CLIENT_SUBNET, DNS_EDNS_OPTION_COOKIE, DNS_EDNS_OPTION_DAU,
    DNS_EDNS_OPTION_DHU, DNS_EDNS_OPTION_EXPIRE, DNS_EDNS_OPTION_EXTENDED_ERROR,
    DNS_EDNS_OPTION_N3U, DNS_EDNS_OPTION_NSID, DNS_EDNS_OPTION_PADDING,
    DNS_EDNS_OPTION_TCP_KEEPALIVE, DNS_FLAG_AUTHENTIC_DATA, DNS_FLAG_AUTHORITATIVE,
    DNS_FLAG_CHECKING_DISABLED, DNS_FLAG_QR_RESPONSE, DNS_FLAG_RECURSION_AVAILABLE,
    DNS_FLAG_RECURSION_DESIRED, DNS_FLAG_TRUNCATED, DNS_HEADER_LEN, DNS_OPCODE_DSO,
    DNS_OPCODE_IQUERY, DNS_OPCODE_NOTIFY, DNS_OPCODE_QUERY, DNS_OPCODE_STATUS, DNS_OPCODE_UPDATE,
    DNS_PORT, DNS_RCODE_DSOTYPENI, DNS_RCODE_FORMERR, DNS_RCODE_NOERROR, DNS_RCODE_NOTAUTH,
    DNS_RCODE_NOTIMP, DNS_RCODE_NOTZONE, DNS_RCODE_NXDOMAIN, DNS_RCODE_NXRRSET, DNS_RCODE_REFUSED,
    DNS_RCODE_SERVFAIL, DNS_RCODE_YXDOMAIN, DNS_RCODE_YXRRSET, DNS_SVCB_KEY_ALPN,
    DNS_SVCB_KEY_DOHPATH, DNS_SVCB_KEY_ECH, DNS_SVCB_KEY_IPV4HINT, DNS_SVCB_KEY_IPV6HINT,
    DNS_SVCB_KEY_MANDATORY, DNS_SVCB_KEY_NO_DEFAULT_ALPN, DNS_SVCB_KEY_PORT, DNS_TYPE_A,
    DNS_TYPE_AAAA, DNS_TYPE_CNAME, DNS_TYPE_DNSKEY, DNS_TYPE_DS, DNS_TYPE_HTTPS, DNS_TYPE_MX,
    DNS_TYPE_NS, DNS_TYPE_NSEC, DNS_TYPE_NSEC3, DNS_TYPE_NSEC3PARAM, DNS_TYPE_OPT, DNS_TYPE_PTR,
    DNS_TYPE_RRSIG, DNS_TYPE_SOA, DNS_TYPE_SRV, DNS_TYPE_SVCB, DNS_TYPE_TLSA, DNS_TYPE_TXT,
    ETHERTYPE_ARP, ETHERTYPE_IPV4, ETHERTYPE_IPV6, ETHERTYPE_VLAN, ICMPV6_DESTINATION_UNREACHABLE,
    ICMPV6_ECHO_REPLY, ICMPV6_ECHO_REQUEST, ICMPV6_PACKET_TOO_BIG, ICMPV6_PARAMETER_PROBLEM,
    ICMPV6_TIME_EXCEEDED, ICMP_ADDRESS_MASK_REPLY, ICMP_ADDRESS_MASK_REQUEST,
    ICMP_ALTERNATE_HOST_ADDRESS,
    ICMP_CODE_DU_COMM_ADMIN_PROHIBITED, ICMP_CODE_DU_DEST_HOST_UNKNOWN,
    ICMP_CODE_DU_DEST_NETWORK_UNKNOWN, ICMP_CODE_DU_FRAGMENTATION_NEEDED,
    ICMP_CODE_DU_HOST_ADMIN_PROHIBITED, ICMP_CODE_DU_HOST_PRECEDENCE_VIOLATION,
    ICMP_CODE_DU_HOST_UNREACHABLE, ICMP_CODE_DU_HOST_UNREACHABLE_TOS,
    ICMP_CODE_DU_NETWORK_ADMIN_PROHIBITED, ICMP_CODE_DU_NETWORK_UNREACHABLE_TOS,
    ICMP_CODE_DU_NET_UNREACHABLE, ICMP_CODE_DU_PORT_UNREACHABLE, ICMP_CODE_DU_PRECEDENCE_CUTOFF,
    ICMP_CODE_DU_PROTOCOL_UNREACHABLE, ICMP_CODE_DU_SOURCE_HOST_ISOLATED,
    ICMP_CODE_DU_SOURCE_ROUTE_FAILED, ICMP_CODE_EXTENDED_ECHO_REPLY_MALFORMED_QUERY,
    ICMP_CODE_EXTENDED_ECHO_REPLY_MULTIPLE_INTERFACES, ICMP_CODE_EXTENDED_ECHO_REPLY_NO_ERROR,
    ICMP_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_INTERFACE,
    ICMP_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_TABLE_ENTRY, ICMP_CODE_PARAMETER_PROBLEM_BAD_LENGTH,
    ICMP_CODE_PARAMETER_PROBLEM_MISSING_OPTION, ICMP_CODE_PARAMETER_PROBLEM_POINTER,
    ICMP_CODE_PHOTURIS_AUTHENTICATION_FAILED, ICMP_CODE_PHOTURIS_BAD_SPI,
    ICMP_CODE_PHOTURIS_DECOMPRESSION_FAILED, ICMP_CODE_PHOTURIS_DECRYPTION_FAILED,
    ICMP_CODE_PHOTURIS_NEED_AUTHENTICATION, ICMP_CODE_PHOTURIS_NEED_AUTHORIZATION,
    ICMP_CODE_REDIRECT_HOST, ICMP_CODE_REDIRECT_NETWORK, ICMP_CODE_REDIRECT_TOS_HOST,
    ICMP_CODE_REDIRECT_TOS_NETWORK, ICMP_CODE_ROUTER_ADVERTISEMENT_NORMAL,
    ICMP_CODE_ROUTER_ADVERTISEMENT_NO_COMMON_TRAFFIC, ICMP_CODE_TIME_EXCEEDED_FRAGMENT_REASSEMBLY,
    ICMP_CODE_TIME_EXCEEDED_TTL, ICMP_DATAGRAM_CONVERSION_ERROR, ICMP_DESTINATION_UNREACHABLE,
    ICMP_DOMAIN_NAME_REPLY, ICMP_DOMAIN_NAME_REQUEST, ICMP_ECHO_REPLY, ICMP_ECHO_REQUEST,
    ICMP_EXPERIMENTAL_253, ICMP_EXPERIMENTAL_254, ICMP_EXTENDED_ECHO_REPLY,
    ICMP_EXTENDED_ECHO_REQUEST, ICMP_EXTENSION_CLASS_INTERFACE_INFO, ICMP_EXTENSION_CLASS_MPLS,
    ICMP_EXTENSION_CTYPE_MPLS_INCOMING, ICMP_INFORMATION_REPLY, ICMP_INFORMATION_REQUEST,
    ICMP_INTERFACE_AFI_IPV4, ICMP_INTERFACE_AFI_IPV6, ICMP_INTERFACE_CTYPE_IFINDEX,
    ICMP_INTERFACE_CTYPE_IP_ADDRESS, ICMP_INTERFACE_CTYPE_MTU, ICMP_INTERFACE_CTYPE_NAME,
    ICMP_INTERFACE_ROLE_INCOMING, ICMP_INTERFACE_ROLE_NEXT_HOP, ICMP_INTERFACE_ROLE_OUTGOING,
    ICMP_INTERFACE_ROLE_SUB_IP_INCOMING, ICMP_IPV6_I_AM_HERE, ICMP_IPV6_WHERE_ARE_YOU,
    ICMP_MOBILE_HOST_REDIRECT, ICMP_MOBILE_REGISTRATION_REPLY, ICMP_MOBILE_REGISTRATION_REQUEST,
    ICMP_PARAMETER_PROBLEM, ICMP_PHOTURIS, ICMP_REDIRECT, ICMP_RESERVED_255,
    ICMP_RESERVED_ROBUSTNESS_EXPERIMENT_FIRST, ICMP_RESERVED_ROBUSTNESS_EXPERIMENT_LAST,
    ICMP_RESERVED_SECURITY, ICMP_ROUTER_ADVERTISEMENT, ICMP_ROUTER_SOLICITATION,
    ICMP_ROUTER_ADVERTISEMENT_ENTRY_WORDS, ICMP_SEAMOBY_EXPERIMENTAL, ICMP_SKIP,
    ICMP_SOURCE_QUENCH, ICMP_TIMESTAMP, ICMP_TIMESTAMP_REPLY, ICMP_TIME_EXCEEDED, ICMP_TRACEROUTE,
    IPPROTO_ICMP, IPPROTO_ICMPV6, IPPROTO_IPV6,
    IPPROTO_IPV6_DSTOPTS, IPPROTO_IPV6_FRAGMENT, IPPROTO_IPV6_HOPOPTS, IPPROTO_IPV6_ROUTE,
    IPPROTO_TCP, IPPROTO_UDP, IPV4_FLAG_DONT_FRAGMENT, IPV4_FLAG_MORE_FRAGMENTS,
    IPV4_FLAG_RESERVED, IPV4_OPTION_EOL, IPV4_OPTION_LOOSE_SOURCE_ROUTE, IPV4_OPTION_NOP,
    IPV4_OPTION_RECORD_ROUTE, IPV4_OPTION_STRICT_SOURCE_ROUTE, IPV4_OPTION_TRACEROUTE,
    IPV6_ROUTING_TYPE_MOBILE, IPV6_ROUTING_TYPE_SEGMENT, IPV6_SEGMENT_POLICY_EGRESS,
    IPV6_SEGMENT_POLICY_INGRESS, IPV6_SEGMENT_POLICY_SOURCE_ADDRESS, IPV6_SEGMENT_POLICY_UNSET,
    TCP_EDO_HEADER_AND_SEGMENT_LEN, TCP_EDO_HEADER_LEN, TCP_EDO_REQUEST_LEN, TCP_FLAG_ACK,
    TCP_FLAG_CWR, TCP_FLAG_ECE, TCP_FLAG_FIN, TCP_FLAG_NS, TCP_FLAG_PSH, TCP_FLAG_RST,
    TCP_FLAG_SYN, TCP_FLAG_URG, TCP_OPTION_EDO, TCP_OPTION_EOL, TCP_OPTION_FAST_OPEN,
    TCP_OPTION_MPTCP, TCP_OPTION_MSS, TCP_OPTION_NOP, TCP_OPTION_SACK, TCP_OPTION_SACK_PERMITTED,
    TCP_OPTION_TIMESTAMP, TCP_OPTION_WINDOW_SCALE, UDP_HEADER_LEN, UDP_OPTION_APC,
    UDP_OPTION_AUTH, UDP_OPTION_EOL, UDP_OPTION_EXP, UDP_OPTION_FRAG, UDP_OPTION_MDS,
    UDP_OPTION_MRDS, UDP_OPTION_NOP, UDP_OPTION_REQ, UDP_OPTION_RES,
    UDP_OPTION_RESERVED_SAFE_END, UDP_OPTION_RESERVED_SAFE_START, UDP_OPTION_RESERVED_UNSAFE,
    UDP_OPTION_TIME, UDP_OPTION_UCMP, UDP_OPTION_UENC, UDP_OPTION_UEXP,
    UDP_OPTION_UNASSIGNED_SAFE_END, UDP_OPTION_UNASSIGNED_SAFE_START,
    UDP_OPTION_UNASSIGNED_UNSAFE_END, UDP_OPTION_UNASSIGNED_UNSAFE_START,
};
pub use registry::{
    EthertypeBindingContext, Ipv4ProtocolBindingContext, Ipv6NextHeaderBindingContext,
    ProtocolRegistry, TcpBindingContext, UdpBindingContext,
};

pub use net::{
    default_interface, default_interface_in, default_interface_name, find_interface,
    find_interface_in, get_ip_strings, get_ips, get_my_ip, get_my_ip_in, get_my_ipv6,
    get_my_ipv6_in, get_my_mac, get_my_mac_in, interface_for, interface_for_in, interfaces,
    parse_ip_range, parse_numbers, reply_filter, reply_matches, send_packet, send_packets,
    send_plan, send_recv_packet, send_recv_packets, BatchSend, BatchSendEntry, BatchSendRecv,
    BatchSendRecvEntry, BatchSendRecvReport, BatchSendReport, InterfaceAddress, InterfaceInfo,
    Ipv4Range, NetError, PacketBatchSendExt, PacketBatchSendRecvExt, PacketSendExt,
    PacketSendRecvExt, RawSender, ReplyMatcher, SendMode, SendOptions, SendPlan, SendRecv,
    SendRecvOptions, SendRecvReport, SendReport, SendTarget, SocketSend, SocketSender,
};
pub use pcap::{
    dump_pcap, read_pcap, read_pcap_filtered, Capture, CaptureControl, CaptureHandle, FileSniffer,
    PcapError, PcapHeader, PcapLinkType, PcapPacket, PcapReader, PcapRecord, PcapRecords,
    PcapTimestamp, PcapWriter, PcapWriterOptions, Sniffer, TimestampPrecision,
};

/// Core packet and protocol APIs.
pub mod core {
    pub use crate::checksum;
    pub use crate::endian;
    pub use crate::error;
    pub use crate::field;
    pub use crate::mac;
    pub use crate::packet;
    pub use crate::protocols;
    pub use crate::registry;
    pub use crate::{
        arp_hardware_type_label, arp_protocol_type_label, decode_dns_name, decode_dns_name_typed,
        decode_tftp_server_addresses, dns_type_name, edns_option_code_name, hexdump, option_meta,
        option_name, option_status, scan_dhcp_option_segments, svcb_param_key_name,
        typed_option_value, udp_option_kind_class, udp_option_kind_is_unsafe,
        udp_option_kind_is_unsupported, Arp, ArpOperation, ClientNetworkDeviceInterface,
        ClientSystemArchitecture, CompiledPacket, CrafterError, Dhcp, DhcpAuthAlgorithm,
        DhcpAuthProtocol, DhcpAuthentication, DhcpClasslessRoute, DhcpClientIdentifier,
        DhcpClientUuid, DhcpDataSource, DhcpForcerenewNonceCapable, DhcpMalformed, DhcpMessageType,
        DhcpOption, DhcpOptionArea, DhcpOptionCode, DhcpOptionFormat, DhcpOptionKind,
        DhcpOptionMeta, DhcpOptionSegment, DhcpOptionStatus, DhcpOptionValue, DhcpRelayAgentInfo,
        DhcpRelaySuboption, DhcpRelayVendorSpecific, DhcpReplayDetectionMethod, DhcpState,
        DhcpStaticRoute, DhcpStatusCode, DhcpStatusCodeOption, DhcpUserClass, DhcpVendorClassData,
        DhcpVendorIdentifyingOption, DhcpVendorSuboption, DhcpVssInfo, Dns, DnsName, DnsQuestion,
        DnsRecord, DnsRecordData, DnsTypeBitmaps, Dot1Q, EdnsOption, Ethernet,
        EthertypeBindingContext, Field, FieldState, Icmp, IcmpAddressMask, IcmpExtension,
        IcmpExtensionInterfaceInfo, IcmpExtensionMpls, IcmpExtensionObject,
        IcmpInterfaceIpAddress, IcmpKind, IcmpLayer, IcmpQuotedIpv4,
        IcmpRouterAdvertisementEntry, IcmpTimestamp, Icmpv6, IntoPacket, IpProtocol, Ipv4,
        Ipv4Option, Ipv4OptionIter, Ipv4ProtocolBindingContext, Ipv4RouteOptionKind, Ipv6,
        Ipv6FragmentHeader,
        Ipv6MobileRoutingHeader,
        Ipv6NextHeaderBindingContext,
        Ipv6RoutingHeader, Ipv6SegmentRoutingHeader, Layer, LayerContext, LinkType, LinuxSll,
        MacAddr, NetworkLayer,
        NullByteOrder, NullLoopback, OptionOverload, Packet, ProtocolRegistry, Raw, Result,
        SipServers, SvcParam, SvcParams, Tcp, TcpBindingContext, TcpExtendedDataOffset, TcpOption,
        TcpOptionIter, TcpSackBlock, TransportChecksumContext, Udp, UdpBindingContext,
        UdpChecksumStatus, UdpOption, UdpOptionIter, UdpOptionKindClass, UdpOptionStatus,
        UdpOptions, Vlan, ARP_HRD_ATM, ARP_HRD_ETHERNET, ARP_HRD_FIBRE_CHANNEL, ARP_HRD_IEEE_802,
        ARP_HRD_INFINIBAND, ARP_HRD_MAPOS, ARP_OP_ARP_NAK, ARP_OP_DRARP_ERROR, ARP_OP_DRARP_REPLY,
        ARP_OP_DRARP_REQUEST, ARP_OP_EXP1, ARP_OP_EXP2, ARP_OP_INARP_REPLY, ARP_OP_INARP_REQUEST,
        ARP_OP_MAPOS_UNARP, ARP_OP_RARP_REPLY, ARP_OP_RARP_REQUEST, ARP_OP_REPLY, ARP_OP_REQUEST,
        ARP_OP_RESERVED, ARP_OP_RESERVED_MAX, ARP_PRO_IPV4, BOOTP_REPLY, BOOTP_REQUEST, DHCP_ACK,
        DHCP_CLIENT_PORT, DHCP_DECLINE, DHCP_DISCOVER, DHCP_HTYPE_ETHERNET, DHCP_INFORM,
        DHCP_MAGIC_COOKIE, DHCP_MAGIC_COOKIE_LEN, DHCP_MIN_LEN, DHCP_NAK, DHCP_OFFER,
        DHCP_OPTION_BROADCAST_ADDRESS, DHCP_OPTION_CLIENT_IDENTIFIER, DHCP_OPTION_DOMAIN_NAME,
        DHCP_OPTION_DOMAIN_NAME_SERVER, DHCP_OPTION_END, DHCP_OPTION_HOST_NAME,
        DHCP_OPTION_IP_ADDRESS_LEASE_TIME, DHCP_OPTION_MESSAGE_TYPE, DHCP_OPTION_OVERLOAD,
        DHCP_OPTION_PAD, DHCP_OPTION_PARAMETER_REQUEST_LIST, DHCP_OPTION_PRIVATE_USE_END,
        DHCP_OPTION_PRIVATE_USE_START, DHCP_OPTION_REBINDING_TIME,
        DHCP_OPTION_RELAY_AGENT_INFORMATION, DHCP_OPTION_RENEWAL_TIME,
        DHCP_OPTION_REQUESTED_IP_ADDRESS, DHCP_OPTION_ROUTER, DHCP_OPTION_SERVER_IDENTIFIER,
        DHCP_OPTION_SUBNET_MASK, DHCP_OVERLOAD_BOTH, DHCP_OVERLOAD_FILE, DHCP_OVERLOAD_SNAME,
        DHCP_RELAY_FLAG_UNICAST, DHCP_RELAY_SUBOPTION_ACCESS_NETWORK_NAME,
        DHCP_RELAY_SUBOPTION_ACCESS_POINT_BSSID, DHCP_RELAY_SUBOPTION_ACCESS_POINT_NAME,
        DHCP_RELAY_SUBOPTION_ACCESS_TECHNOLOGY_TYPE, DHCP_RELAY_SUBOPTION_AUTHENTICATION,
        DHCP_RELAY_SUBOPTION_CIRCUIT_ID, DHCP_RELAY_SUBOPTION_DOCSIS_DEVICE_CLASS,
        DHCP_RELAY_SUBOPTION_LINK_SELECTION, DHCP_RELAY_SUBOPTION_OPERATOR_IDENTIFIER,
        DHCP_RELAY_SUBOPTION_OPERATOR_REALM, DHCP_RELAY_SUBOPTION_RADIUS_ATTRIBUTES,
        DHCP_RELAY_SUBOPTION_RELAY_AGENT_ID, DHCP_RELAY_SUBOPTION_RELAY_FLAGS,
        DHCP_RELAY_SUBOPTION_RELAY_SOURCE_PORT, DHCP_RELAY_SUBOPTION_REMOTE_ID,
        DHCP_RELAY_SUBOPTION_SERVER_ID_OVERRIDE, DHCP_RELAY_SUBOPTION_SUBSCRIBER_ID,
        DHCP_RELAY_SUBOPTION_VENDOR_SPECIFIC, DHCP_RELAY_SUBOPTION_VSS,
        DHCP_RELAY_SUBOPTION_VSS_CONTROL, DHCP_RELEASE, DHCP_REQUEST, DHCP_SERVER_PORT,
        DHCP_VSS_TYPE_GLOBAL_DEFAULT, DHCP_VSS_TYPE_NVT_ASCII, DHCP_VSS_TYPE_VPN_ID, DNS_CLASS_ANY,
        DNS_CLASS_CH, DNS_CLASS_HS, DNS_CLASS_IN, DNS_CLASS_NONE,
        DNS_EDNS_DEFAULT_UDP_PAYLOAD_SIZE, DNS_EDNS_FLAG_DO, DNS_EDNS_OPTION_CLIENT_SUBNET,
        DNS_EDNS_OPTION_COOKIE, DNS_EDNS_OPTION_DAU, DNS_EDNS_OPTION_DHU, DNS_EDNS_OPTION_EXPIRE,
        DNS_EDNS_OPTION_EXTENDED_ERROR, DNS_EDNS_OPTION_N3U, DNS_EDNS_OPTION_NSID,
        DNS_EDNS_OPTION_PADDING, DNS_EDNS_OPTION_TCP_KEEPALIVE, DNS_FLAG_AUTHENTIC_DATA,
        DNS_FLAG_AUTHORITATIVE, DNS_FLAG_CHECKING_DISABLED, DNS_FLAG_QR_RESPONSE,
        DNS_FLAG_RECURSION_AVAILABLE, DNS_FLAG_RECURSION_DESIRED, DNS_FLAG_TRUNCATED,
        DNS_HEADER_LEN, DNS_OPCODE_DSO, DNS_OPCODE_IQUERY, DNS_OPCODE_NOTIFY, DNS_OPCODE_QUERY,
        DNS_OPCODE_STATUS, DNS_OPCODE_UPDATE, DNS_PORT, DNS_RCODE_DSOTYPENI, DNS_RCODE_FORMERR,
        DNS_RCODE_NOERROR, DNS_RCODE_NOTAUTH, DNS_RCODE_NOTIMP, DNS_RCODE_NOTZONE,
        DNS_RCODE_NXDOMAIN, DNS_RCODE_NXRRSET, DNS_RCODE_REFUSED, DNS_RCODE_SERVFAIL,
        DNS_RCODE_YXDOMAIN, DNS_RCODE_YXRRSET, DNS_SVCB_KEY_ALPN, DNS_SVCB_KEY_DOHPATH,
        DNS_SVCB_KEY_ECH, DNS_SVCB_KEY_IPV4HINT, DNS_SVCB_KEY_IPV6HINT, DNS_SVCB_KEY_MANDATORY,
        DNS_SVCB_KEY_NO_DEFAULT_ALPN, DNS_SVCB_KEY_PORT, DNS_TYPE_A, DNS_TYPE_AAAA, DNS_TYPE_CNAME,
        DNS_TYPE_DNSKEY, DNS_TYPE_DS, DNS_TYPE_HTTPS, DNS_TYPE_MX, DNS_TYPE_NS, DNS_TYPE_NSEC,
        DNS_TYPE_NSEC3, DNS_TYPE_NSEC3PARAM, DNS_TYPE_OPT, DNS_TYPE_PTR, DNS_TYPE_RRSIG,
        DNS_TYPE_SOA, DNS_TYPE_SRV, DNS_TYPE_SVCB, DNS_TYPE_TLSA, DNS_TYPE_TXT, ETHERTYPE_ARP,
        ETHERTYPE_IPV4, ETHERTYPE_IPV6, ETHERTYPE_VLAN, ICMPV6_DESTINATION_UNREACHABLE,
        ICMPV6_ECHO_REPLY, ICMPV6_ECHO_REQUEST, ICMPV6_PACKET_TOO_BIG, ICMPV6_PARAMETER_PROBLEM,
        ICMPV6_TIME_EXCEEDED, ICMP_ADDRESS_MASK_REPLY, ICMP_ADDRESS_MASK_REQUEST,
        ICMP_ALTERNATE_HOST_ADDRESS,
        ICMP_CODE_DU_COMM_ADMIN_PROHIBITED, ICMP_CODE_DU_DEST_HOST_UNKNOWN,
        ICMP_CODE_DU_DEST_NETWORK_UNKNOWN, ICMP_CODE_DU_FRAGMENTATION_NEEDED,
        ICMP_CODE_DU_HOST_ADMIN_PROHIBITED, ICMP_CODE_DU_HOST_PRECEDENCE_VIOLATION,
        ICMP_CODE_DU_HOST_UNREACHABLE, ICMP_CODE_DU_HOST_UNREACHABLE_TOS,
        ICMP_CODE_DU_NETWORK_ADMIN_PROHIBITED, ICMP_CODE_DU_NETWORK_UNREACHABLE_TOS,
        ICMP_CODE_DU_NET_UNREACHABLE, ICMP_CODE_DU_PORT_UNREACHABLE,
        ICMP_CODE_DU_PRECEDENCE_CUTOFF, ICMP_CODE_DU_PROTOCOL_UNREACHABLE,
        ICMP_CODE_DU_SOURCE_HOST_ISOLATED, ICMP_CODE_DU_SOURCE_ROUTE_FAILED,
        ICMP_CODE_EXTENDED_ECHO_REPLY_MALFORMED_QUERY,
        ICMP_CODE_EXTENDED_ECHO_REPLY_MULTIPLE_INTERFACES, ICMP_CODE_EXTENDED_ECHO_REPLY_NO_ERROR,
        ICMP_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_INTERFACE,
        ICMP_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_TABLE_ENTRY, ICMP_CODE_PARAMETER_PROBLEM_BAD_LENGTH,
        ICMP_CODE_PARAMETER_PROBLEM_MISSING_OPTION, ICMP_CODE_PARAMETER_PROBLEM_POINTER,
        ICMP_CODE_PHOTURIS_AUTHENTICATION_FAILED, ICMP_CODE_PHOTURIS_BAD_SPI,
        ICMP_CODE_PHOTURIS_DECOMPRESSION_FAILED, ICMP_CODE_PHOTURIS_DECRYPTION_FAILED,
        ICMP_CODE_PHOTURIS_NEED_AUTHENTICATION, ICMP_CODE_PHOTURIS_NEED_AUTHORIZATION,
        ICMP_CODE_REDIRECT_HOST, ICMP_CODE_REDIRECT_NETWORK, ICMP_CODE_REDIRECT_TOS_HOST,
        ICMP_CODE_REDIRECT_TOS_NETWORK, ICMP_CODE_ROUTER_ADVERTISEMENT_NORMAL,
        ICMP_CODE_ROUTER_ADVERTISEMENT_NO_COMMON_TRAFFIC,
        ICMP_CODE_TIME_EXCEEDED_FRAGMENT_REASSEMBLY, ICMP_CODE_TIME_EXCEEDED_TTL,
        ICMP_DATAGRAM_CONVERSION_ERROR, ICMP_DESTINATION_UNREACHABLE, ICMP_DOMAIN_NAME_REPLY,
        ICMP_DOMAIN_NAME_REQUEST, ICMP_ECHO_REPLY, ICMP_ECHO_REQUEST, ICMP_EXPERIMENTAL_253,
        ICMP_EXPERIMENTAL_254, ICMP_EXTENDED_ECHO_REPLY, ICMP_EXTENDED_ECHO_REQUEST,
        ICMP_EXTENSION_CLASS_INTERFACE_INFO, ICMP_EXTENSION_CLASS_MPLS,
        ICMP_EXTENSION_CTYPE_MPLS_INCOMING, ICMP_INFORMATION_REPLY, ICMP_INFORMATION_REQUEST,
        ICMP_INTERFACE_AFI_IPV4, ICMP_INTERFACE_AFI_IPV6, ICMP_INTERFACE_CTYPE_IFINDEX,
        ICMP_INTERFACE_CTYPE_IP_ADDRESS, ICMP_INTERFACE_CTYPE_MTU, ICMP_INTERFACE_CTYPE_NAME,
        ICMP_INTERFACE_ROLE_INCOMING, ICMP_INTERFACE_ROLE_NEXT_HOP, ICMP_INTERFACE_ROLE_OUTGOING,
        ICMP_INTERFACE_ROLE_SUB_IP_INCOMING, ICMP_IPV6_I_AM_HERE, ICMP_IPV6_WHERE_ARE_YOU,
        ICMP_MOBILE_HOST_REDIRECT, ICMP_MOBILE_REGISTRATION_REPLY,
        ICMP_MOBILE_REGISTRATION_REQUEST, ICMP_PARAMETER_PROBLEM, ICMP_PHOTURIS, ICMP_REDIRECT,
        ICMP_RESERVED_255, ICMP_RESERVED_ROBUSTNESS_EXPERIMENT_FIRST,
        ICMP_RESERVED_ROBUSTNESS_EXPERIMENT_LAST, ICMP_RESERVED_SECURITY,
        ICMP_ROUTER_ADVERTISEMENT, ICMP_ROUTER_ADVERTISEMENT_ENTRY_WORDS,
        ICMP_ROUTER_SOLICITATION, ICMP_SEAMOBY_EXPERIMENTAL, ICMP_SKIP, ICMP_SOURCE_QUENCH,
        ICMP_TIMESTAMP, ICMP_TIMESTAMP_REPLY, ICMP_TIME_EXCEEDED, ICMP_TRACEROUTE, IPPROTO_ICMP,
        IPPROTO_ICMPV6, IPPROTO_IPV6, IPPROTO_IPV6_DSTOPTS,
        IPPROTO_IPV6_FRAGMENT, IPPROTO_IPV6_HOPOPTS, IPPROTO_IPV6_ROUTE, IPPROTO_TCP, IPPROTO_UDP,
        IPV4_FLAG_DONT_FRAGMENT, IPV4_FLAG_MORE_FRAGMENTS, IPV4_FLAG_RESERVED, IPV4_OPTION_EOL,
        IPV4_OPTION_LOOSE_SOURCE_ROUTE, IPV4_OPTION_NOP, IPV4_OPTION_RECORD_ROUTE,
        IPV4_OPTION_STRICT_SOURCE_ROUTE, IPV4_OPTION_TRACEROUTE, IPV6_ROUTING_TYPE_MOBILE,
        IPV6_ROUTING_TYPE_SEGMENT, IPV6_SEGMENT_POLICY_EGRESS, IPV6_SEGMENT_POLICY_INGRESS,
        IPV6_SEGMENT_POLICY_SOURCE_ADDRESS, IPV6_SEGMENT_POLICY_UNSET,
        TCP_EDO_HEADER_AND_SEGMENT_LEN, TCP_EDO_HEADER_LEN, TCP_EDO_REQUEST_LEN, TCP_FLAG_ACK,
        TCP_FLAG_CWR, TCP_FLAG_ECE, TCP_FLAG_FIN, TCP_FLAG_NS, TCP_FLAG_PSH, TCP_FLAG_RST,
        TCP_FLAG_SYN, TCP_FLAG_URG, TCP_OPTION_EDO, TCP_OPTION_EOL, TCP_OPTION_FAST_OPEN,
        TCP_OPTION_MPTCP, TCP_OPTION_MSS, TCP_OPTION_NOP, TCP_OPTION_SACK,
        TCP_OPTION_SACK_PERMITTED, TCP_OPTION_TIMESTAMP, TCP_OPTION_WINDOW_SCALE, UDP_HEADER_LEN,
        UDP_OPTION_APC, UDP_OPTION_AUTH, UDP_OPTION_EOL, UDP_OPTION_EXP, UDP_OPTION_FRAG,
        UDP_OPTION_MDS, UDP_OPTION_MRDS, UDP_OPTION_NOP, UDP_OPTION_REQ, UDP_OPTION_RES,
        UDP_OPTION_RESERVED_SAFE_END, UDP_OPTION_RESERVED_SAFE_START, UDP_OPTION_RESERVED_UNSAFE,
        UDP_OPTION_TIME, UDP_OPTION_UCMP, UDP_OPTION_UENC, UDP_OPTION_UEXP,
        UDP_OPTION_UNASSIGNED_SAFE_END, UDP_OPTION_UNASSIGNED_SAFE_START,
        UDP_OPTION_UNASSIGNED_UNSAFE_END, UDP_OPTION_UNASSIGNED_UNSAFE_START,
    };
}

/// Common imports for generated packet tools and examples.
pub mod prelude {
    pub use crate::core::*;
    pub use crate::{
        default_interface, default_interface_in, default_interface_name, dump_pcap, find_interface,
        find_interface_in, get_ip_strings, get_ips, get_my_ip, get_my_ip_in, get_my_ipv6,
        get_my_ipv6_in, get_my_mac, get_my_mac_in, interface_for, interface_for_in, interfaces,
        parse_ip_range, parse_numbers, read_pcap, read_pcap_filtered, reply_filter, reply_matches,
        send_packet, send_packets, send_plan, send_recv_packet, send_recv_packets, BatchSend,
        BatchSendEntry, BatchSendRecv, BatchSendRecvEntry, BatchSendRecvReport, BatchSendReport,
        Capture, CaptureControl, CaptureHandle, FileSniffer, InterfaceAddress, InterfaceInfo,
        Ipv4Range, NetError, PacketBatchSendExt, PacketBatchSendRecvExt, PacketSendExt,
        PacketSendRecvExt, PcapError, PcapHeader, PcapLinkType, PcapPacket, PcapReader, PcapRecord,
        PcapRecords, PcapTimestamp, PcapWriter, PcapWriterOptions, RawSender, ReplyMatcher,
        SendMode, SendOptions, SendPlan, SendRecv, SendRecvOptions, SendRecvReport, SendReport,
        SendTarget, Sniffer, SocketSend, SocketSender, TimestampPrecision,
    };
}
