//! Public crate for packet-level network interaction.
//!
//! `crafter` is the only public crate. It exposes a self-contained API for
//! examples, generated tools, and agent-directed packet workflows:
//!
//! - packet construction, decode, checksums, and protocol layers
//! - classic pcap read/write helpers and libpcap-backed wire adapters
//! - interface, send, send/receive, batch, and address helpers
//! - `PacketWire` source/writer backends, `PacketRecord` metadata,
//!   `Sniffer`/`Transmitter` pipelines, and packet transforms
//! - Ethernet, IEEE 802.11/radiotap, LLC/SNAP, IP, transport, and selected
//!   application protocol primitives
//!
//! Public modules are organized as `crafter::core`, `crafter::pcap`,
//! `crafter::net`, `crafter::wire`, and `crafter::prelude`. The `pcap`
//! module is the low-level classic pcap file format and libpcap adapter layer.
//! The `wire` module is the packet-stream API that generated tools should use
//! for backend-neutral capture, transforms, and transmission. Most examples
//! should start with `use crafter::prelude::*;`.
//!
//! Local examples use dry-run send plans or offline pcaps unless live behavior
//! is explicitly requested.
//!
//! ```rust
//! use crafter::prelude::*;
//! use std::net::Ipv4Addr;
//!
//! # fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
//! let packet = Ipv4::new()
//!     .src(Ipv4Addr::new(192, 0, 2, 10))
//!     .dst(Ipv4Addr::new(198, 51, 100, 20))
//!     / Icmpv4::echo_request().id(0x4242).seq(1)
//!     / Raw::from("hello");
//!
//! let compiled = packet.compile()?;
//! println!("{}", packet.summary());
//! println!("{}", compiled.hexdump());
//! # Ok(())
//! # }
//! ```
//!
//! Wi-Fi stacks use the same offline packet model. IP over IEEE 802.11 is
//! represented with explicit LLC/SNAP, and the example below only compiles,
//! decodes, and inspects synthetic bytes.
//!
//! ```rust
//! use crafter::prelude::*;
//! use std::net::Ipv4Addr;
//!
//! # fn main() -> std::result::Result<(), Box<dyn std::error::Error>> {
//! let sta = MacAddr::new([0x00, 0x00, 0x5e, 0x00, 0x53, 0x01]);
//! let ap = MacAddr::new([0x00, 0x00, 0x5e, 0x00, 0x53, 0x02]);
//! let dot11 = Dot11::data();
//! let to_ds = dot11.frame_control_value().with_to_ds(true);
//!
//! let packet = Radiotap::new()
//!     / dot11
//!         .frame_control(to_ds)
//!         .addr1(ap)
//!         .addr2(sta)
//!         .addr3(ap)
//!         .sequence_number(1)
//!     / LlcSnap::new().ethertype(ETHERTYPE_IPV4)
//!     / Ipv4::new()
//!         .src(Ipv4Addr::new(192, 0, 2, 10))
//!         .dst(Ipv4Addr::new(198, 51, 100, 20))
//!     / Icmpv4::echo_request().id(0x4242).seq(1)
//!     / Raw::from("hello");
//!
//! let compiled = packet.compile()?;
//! let decoded = Packet::decode_from_link(LinkType::Radiotap, compiled.as_bytes())?;
//! assert!(decoded.layer::<Radiotap>().is_some());
//! assert!(decoded.layer::<Dot11>().is_some());
//! assert!(decoded.layer::<LlcSnap>().is_some());
//! assert!(decoded.layer::<Ipv4>().is_some());
//! let _show = decoded.show();
//! let _hexdump = compiled.hexdump();
//! # Ok(())
//! # }
//! ```

#![forbid(unsafe_code)]

#[cfg(test)]
#[macro_use]
#[path = "../tests/support/mod.rs"]
mod test_support;

pub mod checksum;
pub mod endian;
pub mod error;
pub mod field;
pub mod mac;
pub mod packet;
pub mod protocols;
pub mod registry;

pub mod net;
pub mod pcap;
pub mod wire;

pub use error::{CrafterError, Result};
pub use field::{Field, FieldState};
pub use mac::MacAddr;
pub use packet::{
    hexdump, CompiledPacket, IntoPacket, Layer, LayerContext, LinkType, NetworkLayer, Packet, Raw,
    TransportChecksumContext,
};
pub use protocols::{
    arp_hardware_type_label, arp_protocol_type_label, decode_dns_name, decode_dns_name_typed,
    decode_tftp_server_addresses, dns_type_name, eapol_descriptor_type_label, eapol_type_label,
    edns_option_code_name, ipv6_fragment_header_status_label, ipv6_router_alert_value_label,
    ipv6_routing_type_label, ipv6_routing_type_status, ndp_option_type_is_known,
    ndp_option_type_name, ndp_rdnss_length_units, option_meta, option_name, option_status,
    rsn_akm_suite_label, rsn_cipher_suite_label, scan_dhcp_option_segments, svcb_param_key_name,
    tcp_option_kind_class, tcp_option_kind_is_assigned, tcp_option_kind_is_experimental,
    typed_option_value, udp_option_kind_class, udp_option_kind_is_unsafe,
    udp_option_kind_is_unsupported, Ah, Arp, ArpOperation, ClientNetworkDeviceInterface,
    ClientSystemArchitecture, Dhcp, DhcpAuthAlgorithm, DhcpAuthProtocol, DhcpAuthentication,
    DhcpClasslessRoute, DhcpClientIdentifier, DhcpClientUuid, DhcpDataSource,
    DhcpForcerenewNonceCapable, DhcpMalformed, DhcpMessageType, DhcpOption, DhcpOptionArea,
    DhcpOptionCode, DhcpOptionFormat, DhcpOptionKind, DhcpOptionMeta, DhcpOptionSegment,
    DhcpOptionStatus, DhcpOptionValue, DhcpRelayAgentInfo, DhcpRelaySuboption,
    DhcpRelayVendorSpecific, DhcpReplayDetectionMethod, DhcpState, DhcpStaticRoute, DhcpStatusCode,
    DhcpStatusCodeOption, DhcpUserClass, DhcpVendorClassData, DhcpVendorIdentifyingOption,
    DhcpVendorSuboption, DhcpVssInfo, Dns, DnsName, DnsQuestion, DnsRecord, DnsRecordData,
    DnsTypeBitmaps, Dot11, Dot11ActionFixedFields, Dot11AssociationRequestFixedFields,
    Dot11AssociationResponseFixedFields, Dot11AuthenticationFixedFields, Dot11BeaconFixedFields,
    Dot11ControlSubtype, Dot11DataSubtype, Dot11FrameControl, Dot11FrameType,
    Dot11ManagementFixedFields, Dot11ManagementSubtype, Dot11QosControl,
    Dot11ReasonCodeFixedFields, Dot11ReassociationRequestFixedFields, Dot11SequenceControl, Dot1Q,
    Dscp, Eapol, EapolDescriptorType, EapolKey, EapolKeyInformation, EapolType, Ecn, EdnsOption,
    EncryptionAlgorithm, Esp, Ethernet, IcmpExtension, IcmpExtensionInterfaceId,
    IcmpExtensionInterfaceInfo, IcmpExtensionMpls, IcmpExtensionObject, IcmpInterfaceIpAddress,
    IcmpKind, IcmpLayer, Icmpv4, Icmpv4AddressMask, Icmpv4QuotedIp, Icmpv4RouterAdvertisementEntry,
    Icmpv4Timestamp, Icmpv6, Icmpv6Body, Icmpv6ErrorBody, IntegrityAlgorithm, IpsecMode, Ipv4,
    Ipv4ChecksumStatus, Ipv4FragmentInfo, Ipv4Option, Ipv4OptionIter, Ipv4OptionKind, Ipv4Protocol,
    Ipv4RouteOptionKind, Ipv6, Ipv6DestinationOptionsHeader, Ipv6FragmentHeader,
    Ipv6FragmentHeaderStatus, Ipv6HopByHopOptionsHeader, Ipv6MobileRoutingHeader,
    Ipv6MobileRoutingHeaderStatus, Ipv6Option, Ipv6OptionAction, Ipv6OptionIter, Ipv6RoutingHeader,
    Ipv6RoutingTypeStatus, Ipv6SegmentRoutingHeader, LinuxSll, LlcSnap, Mldv2Query, Mldv2Report,
    MulticastAddressRecord, MulticastListenerMessage, MulticastRecordType, NdpOption, NdpOptions,
    NeighborAdvertisement, NeighborSolicitation, NodeInformation, NullByteOrder, NullLoopback,
    OptionOverload, Pref64Plc, Prf, Radiotap, Redirect, RouterAdvertisement, RouterSolicitation,
    RsnAkmSuite, RsnCapabilities, RsnCipherSuite, RsnEapolKeyHandshakeMessage,
    RsnEapolKeyHandshakeMetadata, RsnInformation, RsnSuiteSelector, SecurityAssociation,
    SipServers, SvcParam, SvcParams, Tcp, TcpExtendedDataOffset, TcpOption, TcpOptionIter,
    TcpOptionKindClass, TcpSackBlock, Udp, UdpChecksumStatus, UdpOption, UdpOptionIter,
    UdpOptionKindClass, UdpOptionStatus, UdpOptions, Vlan, AH_FIXED_LEN, AH_HIGH_SEQUENCE_LEN,
    AH_LENGTH_UNIT, AH_NEXT_HEADER_LEN, AH_PAYLOAD_LEN_FIELD_LEN, AH_PAYLOAD_LEN_OFFSET,
    AH_RESERVED_LEN, AH_SEQUENCE_LEN, AH_SPI_LEN, ARP_HRD_ATM, ARP_HRD_ETHERNET,
    ARP_HRD_FIBRE_CHANNEL, ARP_HRD_IEEE_802, ARP_HRD_INFINIBAND, ARP_HRD_MAPOS, ARP_OP_ARP_NAK,
    ARP_OP_DRARP_ERROR, ARP_OP_DRARP_REPLY, ARP_OP_DRARP_REQUEST, ARP_OP_EXP1, ARP_OP_EXP2,
    ARP_OP_INARP_REPLY, ARP_OP_INARP_REQUEST, ARP_OP_MAPOS_UNARP, ARP_OP_RARP_REPLY,
    ARP_OP_RARP_REQUEST, ARP_OP_REPLY, ARP_OP_REQUEST, ARP_OP_RESERVED, ARP_OP_RESERVED_MAX,
    ARP_PRO_IPV4, BOOTP_REPLY, BOOTP_REQUEST, DHCP_ACK, DHCP_AUTH_ALGORITHM_HMAC_MD5,
    DHCP_AUTH_HEADER_LEN, DHCP_AUTH_PROTOCOL_CONFIGURATION_TOKEN, DHCP_AUTH_PROTOCOL_DELAYED,
    DHCP_AUTH_PROTOCOL_RECONFIGURE_KEY, DHCP_AUTH_RDM_MONOTONIC_COUNTER,
    DHCP_AUTH_REPLAY_DETECTION_LEN, DHCP_CLIENT_PORT, DHCP_DECLINE, DHCP_DISCOVER,
    DHCP_FORCERENEW_NONCE_TYPE_HMAC_MD5, DHCP_FORCERENEW_NONCE_TYPE_NONCE, DHCP_HTYPE_ETHERNET,
    DHCP_INFORM, DHCP_MAGIC_COOKIE, DHCP_MAGIC_COOKIE_LEN, DHCP_MIN_LEN, DHCP_NAK, DHCP_OFFER,
    DHCP_OPTION_AUTHENTICATION, DHCP_OPTION_BROADCAST_ADDRESS, DHCP_OPTION_CLIENT_IDENTIFIER,
    DHCP_OPTION_DOMAIN_NAME, DHCP_OPTION_DOMAIN_NAME_SERVER, DHCP_OPTION_END,
    DHCP_OPTION_FORCERENEW_NONCE_CAPABLE, DHCP_OPTION_HOST_NAME, DHCP_OPTION_IP_ADDRESS_LEASE_TIME,
    DHCP_OPTION_MESSAGE_TYPE, DHCP_OPTION_OVERLOAD, DHCP_OPTION_PAD,
    DHCP_OPTION_PARAMETER_REQUEST_LIST, DHCP_OPTION_PRIVATE_USE_END, DHCP_OPTION_PRIVATE_USE_START,
    DHCP_OPTION_REBINDING_TIME, DHCP_OPTION_RELAY_AGENT_INFORMATION, DHCP_OPTION_RENEWAL_TIME,
    DHCP_OPTION_REQUESTED_IP_ADDRESS, DHCP_OPTION_ROUTER, DHCP_OPTION_SERVER_IDENTIFIER,
    DHCP_OPTION_SUBNET_MASK, DHCP_OVERLOAD_BOTH, DHCP_OVERLOAD_FILE, DHCP_OVERLOAD_SNAME,
    DHCP_RELAY_FLAG_UNICAST, DHCP_RELAY_SUBOPTION_ACCESS_NETWORK_NAME,
    DHCP_RELAY_SUBOPTION_ACCESS_POINT_BSSID, DHCP_RELAY_SUBOPTION_ACCESS_POINT_NAME,
    DHCP_RELAY_SUBOPTION_ACCESS_TECHNOLOGY_TYPE, DHCP_RELAY_SUBOPTION_AUTHENTICATION,
    DHCP_RELAY_SUBOPTION_CIRCUIT_ID, DHCP_RELAY_SUBOPTION_DOCSIS_DEVICE_CLASS,
    DHCP_RELAY_SUBOPTION_LINK_SELECTION, DHCP_RELAY_SUBOPTION_OPERATOR_IDENTIFIER,
    DHCP_RELAY_SUBOPTION_OPERATOR_REALM, DHCP_RELAY_SUBOPTION_RADIUS_ATTRIBUTES,
    DHCP_RELAY_SUBOPTION_RELAY_AGENT_ID, DHCP_RELAY_SUBOPTION_RELAY_FLAGS,
    DHCP_RELAY_SUBOPTION_RELAY_SOURCE_PORT, DHCP_RELAY_SUBOPTION_REMOTE_ID,
    DHCP_RELAY_SUBOPTION_SERVER_ID_OVERRIDE, DHCP_RELAY_SUBOPTION_SUBSCRIBER_ID,
    DHCP_RELAY_SUBOPTION_VENDOR_SPECIFIC, DHCP_RELAY_SUBOPTION_VSS,
    DHCP_RELAY_SUBOPTION_VSS_CONTROL, DHCP_RELEASE, DHCP_REQUEST, DHCP_SERVER_PORT,
    DHCP_VSS_TYPE_GLOBAL_DEFAULT, DHCP_VSS_TYPE_NVT_ASCII, DHCP_VSS_TYPE_VPN_ID, DNS_CLASS_ANY,
    DNS_CLASS_CH, DNS_CLASS_HS, DNS_CLASS_IN, DNS_CLASS_NONE, DNS_EDNS_DEFAULT_UDP_PAYLOAD_SIZE,
    DNS_EDNS_FLAG_DO, DNS_EDNS_OPTION_CLIENT_SUBNET, DNS_EDNS_OPTION_COOKIE, DNS_EDNS_OPTION_DAU,
    DNS_EDNS_OPTION_DHU, DNS_EDNS_OPTION_EXPIRE, DNS_EDNS_OPTION_EXTENDED_ERROR,
    DNS_EDNS_OPTION_N3U, DNS_EDNS_OPTION_NSID, DNS_EDNS_OPTION_PADDING,
    DNS_EDNS_OPTION_TCP_KEEPALIVE, DNS_FLAG_AUTHENTIC_DATA, DNS_FLAG_AUTHORITATIVE,
    DNS_FLAG_CHECKING_DISABLED, DNS_FLAG_QR_RESPONSE, DNS_FLAG_RECURSION_AVAILABLE,
    DNS_FLAG_RECURSION_DESIRED, DNS_FLAG_TRUNCATED, DNS_HEADER_LEN, DNS_OPCODE_DSO,
    DNS_OPCODE_IQUERY, DNS_OPCODE_NOTIFY, DNS_OPCODE_QUERY, DNS_OPCODE_STATUS, DNS_OPCODE_UPDATE,
    DNS_PORT, DNS_RCODE_DSOTYPENI, DNS_RCODE_FORMERR, DNS_RCODE_NOERROR, DNS_RCODE_NOTAUTH,
    DNS_RCODE_NOTIMP, DNS_RCODE_NOTZONE, DNS_RCODE_NXDOMAIN, DNS_RCODE_NXRRSET, DNS_RCODE_REFUSED,
    DNS_RCODE_SERVFAIL, DNS_RCODE_YXDOMAIN, DNS_RCODE_YXRRSET, DNS_SVCB_KEY_ALPN,
    DNS_SVCB_KEY_DOHPATH, DNS_SVCB_KEY_ECH, DNS_SVCB_KEY_IPV4HINT, DNS_SVCB_KEY_IPV6HINT,
    DNS_SVCB_KEY_MANDATORY, DNS_SVCB_KEY_NO_DEFAULT_ALPN, DNS_SVCB_KEY_PORT, DNS_TYPE_A,
    DNS_TYPE_AAAA, DNS_TYPE_CNAME, DNS_TYPE_DNSKEY, DNS_TYPE_DS, DNS_TYPE_HTTPS, DNS_TYPE_MX,
    DNS_TYPE_NS, DNS_TYPE_NSEC, DNS_TYPE_NSEC3, DNS_TYPE_NSEC3PARAM, DNS_TYPE_OPT, DNS_TYPE_PTR,
    DNS_TYPE_RRSIG, DNS_TYPE_SOA, DNS_TYPE_SRV, DNS_TYPE_SVCB, DNS_TYPE_TLSA, DNS_TYPE_TXT,
    EAPOL_HEADER_LEN, EAPOL_KEY_DESCRIPTOR_MIN_LEN, EAPOL_KEY_DESCRIPTOR_RSN, EAPOL_TYPE_ASF_ALERT,
    EAPOL_TYPE_EAP_PACKET, EAPOL_TYPE_KEY, EAPOL_TYPE_LOGOFF, EAPOL_TYPE_START, EAPOL_VERSION_1,
    EAPOL_VERSION_2, EAPOL_VERSION_3, ESP_HEADER_LEN, ESP_HIGH_SEQUENCE_LEN, ESP_MAX_PAD_LEN,
    ESP_NEXT_HEADER_FIELD_LEN, ESP_PAD_LENGTH_FIELD_LEN, ETHERTYPE_ARP, ETHERTYPE_EAPOL,
    ETHERTYPE_IPV4, ETHERTYPE_IPV6, ETHERTYPE_VLAN,
    ICMPV6_CODE_EXTENDED_ECHO_REPLY_MALFORMED_QUERY,
    ICMPV6_CODE_EXTENDED_ECHO_REPLY_MULTIPLE_INTERFACES, ICMPV6_CODE_EXTENDED_ECHO_REPLY_NO_ERROR,
    ICMPV6_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_INTERFACE,
    ICMPV6_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_TABLE_ENTRY, ICMPV6_DESTINATION_UNREACHABLE,
    ICMPV6_ECHO_REPLY, ICMPV6_ECHO_REQUEST, ICMPV6_EXTENDED_ECHO_REPLY,
    ICMPV6_EXTENDED_ECHO_REPLY_ACTIVE, ICMPV6_EXTENDED_ECHO_REPLY_IPV4,
    ICMPV6_EXTENDED_ECHO_REPLY_IPV6, ICMPV6_EXTENDED_ECHO_REPLY_STATE_DELAY,
    ICMPV6_EXTENDED_ECHO_REPLY_STATE_FAILED, ICMPV6_EXTENDED_ECHO_REPLY_STATE_INCOMPLETE,
    ICMPV6_EXTENDED_ECHO_REPLY_STATE_PROBE, ICMPV6_EXTENDED_ECHO_REPLY_STATE_REACHABLE,
    ICMPV6_EXTENDED_ECHO_REPLY_STATE_RESERVED, ICMPV6_EXTENDED_ECHO_REPLY_STATE_STALE,
    ICMPV6_EXTENDED_ECHO_REQUEST, ICMPV6_EXTENDED_ECHO_REQUEST_L_BIT,
    ICMPV6_INVERSE_ND_ADVERTISEMENT, ICMPV6_INVERSE_ND_SOLICITATION, ICMPV6_MLDV2_REPORT,
    ICMPV6_MULTICAST_LISTENER_DONE, ICMPV6_MULTICAST_LISTENER_QUERY,
    ICMPV6_MULTICAST_LISTENER_REPORT, ICMPV6_NA_FLAGS_RESERVED, ICMPV6_NA_FLAG_OVERRIDE,
    ICMPV6_NA_FLAG_ROUTER, ICMPV6_NA_FLAG_SOLICITED, ICMPV6_NEIGHBOR_ADVERTISEMENT,
    ICMPV6_NEIGHBOR_SOLICITATION, ICMPV6_NODE_INFORMATION_QUERY, ICMPV6_NODE_INFORMATION_RESPONSE,
    ICMPV6_PACKET_TOO_BIG, ICMPV6_PARAMETER_PROBLEM, ICMPV6_RA_DEFAULT_CUR_HOP_LIMIT,
    ICMPV6_RA_DEFAULT_ROUTER_LIFETIME, ICMPV6_RA_FLAGS_RESERVED, ICMPV6_RA_FLAG_MANAGED,
    ICMPV6_RA_FLAG_OTHER, ICMPV6_REDIRECT, ICMPV6_ROUTER_ADVERTISEMENT, ICMPV6_ROUTER_RENUMBERING,
    ICMPV6_ROUTER_SOLICITATION, ICMPV6_TIME_EXCEEDED, ICMP_ADDRESS_MASK_REPLY,
    ICMP_ADDRESS_MASK_REQUEST, ICMP_ALTERNATE_HOST_ADDRESS, ICMP_CODE_DU_COMM_ADMIN_PROHIBITED,
    ICMP_CODE_DU_DEST_HOST_UNKNOWN, ICMP_CODE_DU_DEST_NETWORK_UNKNOWN,
    ICMP_CODE_DU_FRAGMENTATION_NEEDED, ICMP_CODE_DU_HOST_ADMIN_PROHIBITED,
    ICMP_CODE_DU_HOST_PRECEDENCE_VIOLATION, ICMP_CODE_DU_HOST_UNREACHABLE,
    ICMP_CODE_DU_HOST_UNREACHABLE_TOS, ICMP_CODE_DU_NETWORK_ADMIN_PROHIBITED,
    ICMP_CODE_DU_NETWORK_UNREACHABLE_TOS, ICMP_CODE_DU_NET_UNREACHABLE,
    ICMP_CODE_DU_PORT_UNREACHABLE, ICMP_CODE_DU_PRECEDENCE_CUTOFF,
    ICMP_CODE_DU_PROTOCOL_UNREACHABLE, ICMP_CODE_DU_SOURCE_HOST_ISOLATED,
    ICMP_CODE_DU_SOURCE_ROUTE_FAILED, ICMP_CODE_EXTENDED_ECHO_REPLY_MALFORMED_QUERY,
    ICMP_CODE_EXTENDED_ECHO_REPLY_MULTIPLE_INTERFACES, ICMP_CODE_EXTENDED_ECHO_REPLY_NO_ERROR,
    ICMP_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_INTERFACE,
    ICMP_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_TABLE_ENTRY, ICMP_CODE_PARAMETER_PROBLEM_BAD_LENGTH,
    ICMP_CODE_PARAMETER_PROBLEM_MISSING_OPTION, ICMP_CODE_PARAMETER_PROBLEM_POINTER,
    ICMP_CODE_PHOTURIS_AUTHENTICATION_FAILED, ICMP_CODE_PHOTURIS_BAD_SPI,
    ICMP_CODE_PHOTURIS_DECOMPRESSION_FAILED, ICMP_CODE_PHOTURIS_DECRYPTION_FAILED,
    ICMP_CODE_PHOTURIS_NEED_AUTHENTICATION, ICMP_CODE_PHOTURIS_NEED_AUTHORIZATION,
    ICMP_CODE_REDIRECT_HOST, ICMP_CODE_REDIRECT_NETWORK, ICMP_CODE_REDIRECT_TOS_HOST,
    ICMP_CODE_REDIRECT_TOS_NETWORK, ICMP_CODE_ROUTER_ADVERTISEMENT_NORMAL,
    ICMP_CODE_ROUTER_ADVERTISEMENT_NO_COMMON_TRAFFIC, ICMP_CODE_TIME_EXCEEDED_FRAGMENT_REASSEMBLY,
    ICMP_CODE_TIME_EXCEEDED_TTL, ICMP_DATAGRAM_CONVERSION_ERROR, ICMP_DESTINATION_UNREACHABLE,
    ICMP_DOMAIN_NAME_REPLY, ICMP_DOMAIN_NAME_REQUEST, ICMP_ECHO_REPLY, ICMP_ECHO_REQUEST,
    ICMP_EXPERIMENTAL_253, ICMP_EXPERIMENTAL_254, ICMP_EXTENDED_ECHO_REPLY,
    ICMP_EXTENDED_ECHO_REPLY_ACTIVE, ICMP_EXTENDED_ECHO_REPLY_IPV4, ICMP_EXTENDED_ECHO_REPLY_IPV6,
    ICMP_EXTENDED_ECHO_REPLY_STATE_DELAY, ICMP_EXTENDED_ECHO_REPLY_STATE_FAILED,
    ICMP_EXTENDED_ECHO_REPLY_STATE_INCOMPLETE, ICMP_EXTENDED_ECHO_REPLY_STATE_PROBE,
    ICMP_EXTENDED_ECHO_REPLY_STATE_REACHABLE, ICMP_EXTENDED_ECHO_REPLY_STATE_RESERVED,
    ICMP_EXTENDED_ECHO_REPLY_STATE_STALE, ICMP_EXTENDED_ECHO_REQUEST,
    ICMP_EXTENDED_ECHO_REQUEST_L_BIT, ICMP_EXTENSION_CLASS_INTERFACE_ID,
    ICMP_EXTENSION_CLASS_INTERFACE_INFO, ICMP_EXTENSION_CLASS_MPLS,
    ICMP_EXTENSION_CTYPE_MPLS_INCOMING, ICMP_INFORMATION_REPLY, ICMP_INFORMATION_REQUEST,
    ICMP_INTERFACE_AFI_IPV4, ICMP_INTERFACE_AFI_IPV6, ICMP_INTERFACE_CTYPE_IFINDEX,
    ICMP_INTERFACE_CTYPE_IP_ADDRESS, ICMP_INTERFACE_CTYPE_MTU, ICMP_INTERFACE_CTYPE_NAME,
    ICMP_INTERFACE_ID_CTYPE_ADDRESS, ICMP_INTERFACE_ID_CTYPE_INDEX, ICMP_INTERFACE_ID_CTYPE_NAME,
    ICMP_INTERFACE_ROLE_INCOMING, ICMP_INTERFACE_ROLE_NEXT_HOP, ICMP_INTERFACE_ROLE_OUTGOING,
    ICMP_INTERFACE_ROLE_SUB_IP_INCOMING, ICMP_IPV6_I_AM_HERE, ICMP_IPV6_WHERE_ARE_YOU,
    ICMP_MOBILE_HOST_REDIRECT, ICMP_MOBILE_REGISTRATION_REPLY, ICMP_MOBILE_REGISTRATION_REQUEST,
    ICMP_PARAMETER_PROBLEM, ICMP_PHOTURIS, ICMP_REDIRECT, ICMP_RESERVED_255,
    ICMP_RESERVED_ROBUSTNESS_EXPERIMENT_FIRST, ICMP_RESERVED_ROBUSTNESS_EXPERIMENT_LAST,
    ICMP_RESERVED_SECURITY, ICMP_ROUTER_ADVERTISEMENT, ICMP_ROUTER_ADVERTISEMENT_ENTRY_WORDS,
    ICMP_ROUTER_SOLICITATION, ICMP_SEAMOBY_EXPERIMENTAL, ICMP_SKIP, ICMP_SOURCE_QUENCH,
    ICMP_TIMESTAMP, ICMP_TIMESTAMP_REPLY, ICMP_TIME_EXCEEDED, ICMP_TRACEROUTE, IPPROTO_AH,
    IPPROTO_ESP, IPPROTO_EXPERIMENTAL_1, IPPROTO_EXPERIMENTAL_2, IPPROTO_GRE, IPPROTO_ICMP,
    IPPROTO_ICMPV6, IPPROTO_IPV6, IPPROTO_IPV6_AH, IPPROTO_IPV6_DSTOPTS, IPPROTO_IPV6_ESP,
    IPPROTO_IPV6_EXPERIMENTAL_1, IPPROTO_IPV6_EXPERIMENTAL_2, IPPROTO_IPV6_FRAGMENT,
    IPPROTO_IPV6_HIP, IPPROTO_IPV6_HOPOPTS, IPPROTO_IPV6_MOBILITY, IPPROTO_IPV6_NO_NEXT,
    IPPROTO_IPV6_ROUTE, IPPROTO_IPV6_SHIM6, IPPROTO_OSPF, IPPROTO_SCTP, IPPROTO_TCP, IPPROTO_UDP,
    IPV4_FLAG_DONT_FRAGMENT, IPV4_FLAG_MORE_FRAGMENTS, IPV4_FLAG_RESERVED, IPV4_OPTION_EOL,
    IPV4_OPTION_EXPERIMENTAL_1, IPV4_OPTION_EXPERIMENTAL_2, IPV4_OPTION_EXPERIMENTAL_3,
    IPV4_OPTION_EXPERIMENTAL_4, IPV4_OPTION_LOOSE_SOURCE_ROUTE, IPV4_OPTION_NOP,
    IPV4_OPTION_RECORD_ROUTE, IPV4_OPTION_ROUTER_ALERT, IPV4_OPTION_STRICT_SOURCE_ROUTE,
    IPV4_OPTION_TIMESTAMP, IPV4_OPTION_TRACEROUTE, IPV6_MOBILE_ROUTING_HEADER_EXT_LEN,
    IPV6_MOBILE_ROUTING_RESERVED, IPV6_MOBILE_ROUTING_SEGMENTS_LEFT, IPV6_OPTION_HOME_ADDRESS,
    IPV6_OPTION_JUMBO_PAYLOAD, IPV6_OPTION_PAD1, IPV6_OPTION_PADN, IPV6_OPTION_ROUTER_ALERT,
    IPV6_ROUTER_ALERT_ACTIVE_NETWORKS, IPV6_ROUTER_ALERT_MLD, IPV6_ROUTER_ALERT_MPLS_OAM,
    IPV6_ROUTER_ALERT_RESERVED, IPV6_ROUTER_ALERT_RSVP, IPV6_ROUTING_TYPE_CRH16,
    IPV6_ROUTING_TYPE_CRH32, IPV6_ROUTING_TYPE_EXPERIMENTAL_1, IPV6_ROUTING_TYPE_EXPERIMENTAL_2,
    IPV6_ROUTING_TYPE_MOBILE, IPV6_ROUTING_TYPE_NIMROD, IPV6_ROUTING_TYPE_RESERVED,
    IPV6_ROUTING_TYPE_RH0, IPV6_ROUTING_TYPE_RPL, IPV6_ROUTING_TYPE_SEGMENT,
    IPV6_ROUTING_TYPE_SOURCE_ROUTE, IPV6_SEGMENT_POLICY_EGRESS, IPV6_SEGMENT_POLICY_INGRESS,
    IPV6_SEGMENT_POLICY_SOURCE_ADDRESS, IPV6_SEGMENT_POLICY_UNSET, MLDV2_QUERY_MIN_BODY_LEN,
    MLDV2_QUERY_QRV_MASK, MLDV2_QUERY_RESV_MASK, MLDV2_QUERY_S_FLAG, NDP_DNS_LIFETIME_INFINITY,
    NDP_DNS_RESERVED_LEN, NDP_LINK_LAYER_ADDR_ETHERNET_LEN, NDP_MTU_OPTION_LEN,
    NDP_MTU_OPTION_UNITS, NDP_NONCE_MIN_LEN, NDP_OPTION_HEADER_LEN, NDP_OPTION_LENGTH_UNIT,
    NDP_OPT_CAPTIVE_PORTAL, NDP_OPT_DNSSL, NDP_OPT_MTU, NDP_OPT_NONCE, NDP_OPT_PREF64,
    NDP_OPT_PREFIX_INFORMATION, NDP_OPT_RA_FLAGS_EXTENSION, NDP_OPT_RDNSS,
    NDP_OPT_REDIRECTED_HEADER, NDP_OPT_ROUTE_INFORMATION, NDP_OPT_SOURCE_LINK_LAYER_ADDR,
    NDP_OPT_TARGET_LINK_LAYER_ADDR, NDP_PREF64_LEN, NDP_PREF64_PLC_MASK, NDP_PREF64_PREFIX_LEN,
    NDP_PREF64_SCALED_LIFETIME_MAX, NDP_PREF64_SCALED_LIFETIME_SHIFT, NDP_PREF64_UNITS,
    NDP_PREFIX_FLAGS_RESERVED, NDP_PREFIX_FLAG_AUTONOMOUS, NDP_PREFIX_FLAG_ON_LINK,
    NDP_PREFIX_INFORMATION_LEN, NDP_PREFIX_INFORMATION_UNITS, NDP_PREFIX_LIFETIME_INFINITY,
    NDP_PRF_MASK, NDP_PRF_SHIFT, NDP_RA_FLAGS_EXTENSION_BITS_LEN, NDP_RA_FLAGS_EXTENSION_LEN,
    NDP_RA_FLAGS_EXTENSION_UNITS, NDP_RDNSS_ADDRESS_LEN, NDP_REDIRECTED_HEADER_RESERVED_LEN,
    NDP_ROUTE_INFORMATION_LEN_FULL_PREFIX, NDP_ROUTE_INFORMATION_LEN_HALF_PREFIX,
    NDP_ROUTE_INFORMATION_LEN_NO_PREFIX, NDP_ROUTE_LIFETIME_INFINITY, NI_NONCE_LEN,
    NI_QTYPE_IPV4_ADDRESSES, NI_QTYPE_NODE_ADDRESSES, NI_QTYPE_NODE_NAME, NI_QTYPE_NOOP,
    NI_QUERY_CODE_SUBJECT_IPV4, NI_QUERY_CODE_SUBJECT_IPV6, NI_QUERY_CODE_SUBJECT_NAME,
    NI_RESPONSE_CODE_REFUSED, NI_RESPONSE_CODE_SUCCESS, NI_RESPONSE_CODE_UNKNOWN_QTYPE,
    RSN_AKM_SUITE_8021X, RSN_AKM_SUITE_8021X_SHA256, RSN_AKM_SUITE_8021X_SUITE_B,
    RSN_AKM_SUITE_8021X_SUITE_B_192, RSN_AKM_SUITE_AP_PEER_KEY, RSN_AKM_SUITE_EDPKE,
    RSN_AKM_SUITE_FILS_SHA256, RSN_AKM_SUITE_FILS_SHA384, RSN_AKM_SUITE_FT_8021X,
    RSN_AKM_SUITE_FT_8021X_SHA384, RSN_AKM_SUITE_FT_8021X_SHA384_BASIC,
    RSN_AKM_SUITE_FT_8021X_SHA384_CMP_256, RSN_AKM_SUITE_FT_FILS_SHA256,
    RSN_AKM_SUITE_FT_FILS_SHA384, RSN_AKM_SUITE_FT_PSK, RSN_AKM_SUITE_FT_PSK_SHA384,
    RSN_AKM_SUITE_FT_SAE, RSN_AKM_SUITE_FT_SAE_PMK384, RSN_AKM_SUITE_OWE, RSN_AKM_SUITE_PASN,
    RSN_AKM_SUITE_PASN_DEFINED_KEY_WRAP, RSN_AKM_SUITE_PSK, RSN_AKM_SUITE_PSK_SHA256,
    RSN_AKM_SUITE_PSK_SHA384, RSN_AKM_SUITE_SAE, RSN_AKM_SUITE_SAE_PMK384, RSN_AKM_SUITE_TDLS,
    RSN_CAPABILITIES_LEN, RSN_CIPHER_SUITE_AES_128_CMAC, RSN_CIPHER_SUITE_BIP_CMAC_256,
    RSN_CIPHER_SUITE_BIP_GMAC_128, RSN_CIPHER_SUITE_BIP_GMAC_256, RSN_CIPHER_SUITE_CCMP_128,
    RSN_CIPHER_SUITE_CCMP_256, RSN_CIPHER_SUITE_CCM_STAR, RSN_CIPHER_SUITE_GCMP_128,
    RSN_CIPHER_SUITE_GCMP_256, RSN_CIPHER_SUITE_NO_GROUP_ADDRESSED, RSN_CIPHER_SUITE_TKIP,
    RSN_CIPHER_SUITE_USE_GROUP, RSN_SUITE_SELECTOR_LEN, RSN_SUITE_SELECTOR_OUI, RSN_VERSION_1,
    TCP_EDO_HEADER_AND_SEGMENT_LEN, TCP_EDO_HEADER_LEN, TCP_EDO_REQUEST_LEN, TCP_FLAG_ACK,
    TCP_FLAG_AE, TCP_FLAG_CWR, TCP_FLAG_ECE, TCP_FLAG_FIN, TCP_FLAG_NS, TCP_FLAG_PSH, TCP_FLAG_RST,
    TCP_FLAG_SYN, TCP_FLAG_URG, TCP_OPTION_EDO, TCP_OPTION_EOL, TCP_OPTION_FAST_OPEN,
    TCP_OPTION_MPTCP, TCP_OPTION_MSS, TCP_OPTION_NOP, TCP_OPTION_SACK, TCP_OPTION_SACK_PERMITTED,
    TCP_OPTION_TIMESTAMP, TCP_OPTION_WINDOW_SCALE, UDP_HEADER_LEN, UDP_OPTION_APC, UDP_OPTION_AUTH,
    UDP_OPTION_EOL, UDP_OPTION_EXP, UDP_OPTION_FRAG, UDP_OPTION_MDS, UDP_OPTION_MRDS,
    UDP_OPTION_NOP, UDP_OPTION_REQ, UDP_OPTION_RES, UDP_OPTION_RESERVED_SAFE_END,
    UDP_OPTION_RESERVED_SAFE_START, UDP_OPTION_RESERVED_UNSAFE, UDP_OPTION_TIME, UDP_OPTION_UCMP,
    UDP_OPTION_UENC, UDP_OPTION_UEXP, UDP_OPTION_UNASSIGNED_SAFE_END,
    UDP_OPTION_UNASSIGNED_SAFE_START, UDP_OPTION_UNASSIGNED_UNSAFE_END,
    UDP_OPTION_UNASSIGNED_UNSAFE_START,
};
pub use protocols::{
    dot11_category_label, dot11_control_subtype_label, dot11_data_subtype_label,
    dot11_frame_type_label, dot11_management_subtype_label, dot11_subtype_label,
    Dot11TaggedParameter, DOT11_ADDRESS_LEN, DOT11_CAPABILITY_APSD, DOT11_CAPABILITY_CF_POLLABLE,
    DOT11_CAPABILITY_CF_POLL_REQUEST, DOT11_CAPABILITY_CHANNEL_AGILITY,
    DOT11_CAPABILITY_DELAYED_BLOCK_ACK, DOT11_CAPABILITY_DSSS_OFDM, DOT11_CAPABILITY_ESS,
    DOT11_CAPABILITY_IBSS, DOT11_CAPABILITY_IMMEDIATE_BLOCK_ACK, DOT11_CAPABILITY_PBCC,
    DOT11_CAPABILITY_PRIVACY, DOT11_CAPABILITY_QOS, DOT11_CAPABILITY_RADIO_MEASUREMENT,
    DOT11_CAPABILITY_SHORT_PREAMBLE, DOT11_CAPABILITY_SHORT_SLOT_TIME,
    DOT11_CAPABILITY_SPECTRUM_MANAGEMENT, DOT11_CATEGORY_BLOCK_ACK, DOT11_CATEGORY_DLS,
    DOT11_CATEGORY_FAST_BSS_TRANSITION, DOT11_CATEGORY_HT, DOT11_CATEGORY_MESH,
    DOT11_CATEGORY_MULTIHOP, DOT11_CATEGORY_PROTECTED_DUAL_OF_PUBLIC_ACTION, DOT11_CATEGORY_PUBLIC,
    DOT11_CATEGORY_QOS, DOT11_CATEGORY_RADIO_MEASUREMENT, DOT11_CATEGORY_SA_QUERY,
    DOT11_CATEGORY_SELF_PROTECTED, DOT11_CATEGORY_SPECTRUM_MANAGEMENT, DOT11_CATEGORY_TDLS,
    DOT11_CATEGORY_UNPROTECTED_WNM, DOT11_CATEGORY_WNM, DOT11_CONTROL_ONE_ADDRESS_HEADER_LEN,
    DOT11_CONTROL_SUBTYPE_ACK, DOT11_CONTROL_SUBTYPE_BLOCK_ACK,
    DOT11_CONTROL_SUBTYPE_BLOCK_ACK_REQUEST, DOT11_CONTROL_SUBTYPE_CF_END,
    DOT11_CONTROL_SUBTYPE_CF_END_CF_ACK, DOT11_CONTROL_SUBTYPE_CONTROL_WRAPPER,
    DOT11_CONTROL_SUBTYPE_CTS, DOT11_CONTROL_SUBTYPE_PS_POLL, DOT11_CONTROL_SUBTYPE_RTS,
    DOT11_CONTROL_SUBTYPE_TRIGGER, DOT11_CONTROL_TWO_ADDRESS_HEADER_LEN,
    DOT11_DATA_ADDR4_HEADER_LEN, DOT11_DATA_HEADER_LEN, DOT11_DATA_SUBTYPE_CF_ACK,
    DOT11_DATA_SUBTYPE_CF_ACK_CF_POLL, DOT11_DATA_SUBTYPE_CF_POLL, DOT11_DATA_SUBTYPE_DATA,
    DOT11_DATA_SUBTYPE_DATA_CF_ACK, DOT11_DATA_SUBTYPE_DATA_CF_ACK_CF_POLL,
    DOT11_DATA_SUBTYPE_DATA_CF_POLL, DOT11_DATA_SUBTYPE_NULL,
    DOT11_DATA_SUBTYPE_QOS_CF_ACK_CF_POLL, DOT11_DATA_SUBTYPE_QOS_CF_POLL,
    DOT11_DATA_SUBTYPE_QOS_DATA, DOT11_DATA_SUBTYPE_QOS_DATA_CF_ACK,
    DOT11_DATA_SUBTYPE_QOS_DATA_CF_ACK_CF_POLL, DOT11_DATA_SUBTYPE_QOS_DATA_CF_POLL,
    DOT11_DATA_SUBTYPE_QOS_NULL, DOT11_DURATION_ID_LEN, DOT11_FC_FROM_DS, DOT11_FC_MORE_DATA,
    DOT11_FC_MORE_FRAGMENTS, DOT11_FC_ORDER, DOT11_FC_POWER_MANAGEMENT, DOT11_FC_PROTECTED,
    DOT11_FC_PROTOCOL_VERSION_MASK, DOT11_FC_PROTOCOL_VERSION_SHIFT, DOT11_FC_RETRY,
    DOT11_FC_SUBTYPE_MASK, DOT11_FC_SUBTYPE_SHIFT, DOT11_FC_TO_DS, DOT11_FC_TYPE_MASK,
    DOT11_FC_TYPE_SHIFT, DOT11_FRAME_CONTROL_LEN, DOT11_FRAME_TYPE_CONTROL, DOT11_FRAME_TYPE_DATA,
    DOT11_FRAME_TYPE_EXTENSION, DOT11_FRAME_TYPE_MANAGEMENT, DOT11_HT_CONTROL_LEN,
    DOT11_MGMT_ACTION_FIXED_LEN, DOT11_MGMT_ASSOCIATION_REQUEST_FIXED_LEN,
    DOT11_MGMT_ASSOCIATION_RESPONSE_FIXED_LEN, DOT11_MGMT_AUTHENTICATION_FIXED_LEN,
    DOT11_MGMT_BEACON_FIXED_LEN, DOT11_MGMT_DEAUTHENTICATION_FIXED_LEN,
    DOT11_MGMT_DISASSOCIATION_FIXED_LEN, DOT11_MGMT_PROBE_RESPONSE_FIXED_LEN,
    DOT11_MGMT_REASSOCIATION_REQUEST_FIXED_LEN, DOT11_MGMT_REASSOCIATION_RESPONSE_FIXED_LEN,
    DOT11_MGMT_SUBTYPE_ACTION, DOT11_MGMT_SUBTYPE_ACTION_NO_ACK,
    DOT11_MGMT_SUBTYPE_ASSOCIATION_REQUEST, DOT11_MGMT_SUBTYPE_ASSOCIATION_RESPONSE,
    DOT11_MGMT_SUBTYPE_ATIM, DOT11_MGMT_SUBTYPE_AUTHENTICATION, DOT11_MGMT_SUBTYPE_BEACON,
    DOT11_MGMT_SUBTYPE_DEAUTHENTICATION, DOT11_MGMT_SUBTYPE_DISASSOCIATION,
    DOT11_MGMT_SUBTYPE_PROBE_REQUEST, DOT11_MGMT_SUBTYPE_PROBE_RESPONSE,
    DOT11_MGMT_SUBTYPE_REASSOCIATION_REQUEST, DOT11_MGMT_SUBTYPE_REASSOCIATION_RESPONSE,
    DOT11_MGMT_SUBTYPE_TIMING_ADVERTISEMENT, DOT11_MIN_HEADER_LEN, DOT11_QOS_ACK_POLICY_MASK,
    DOT11_QOS_ACK_POLICY_SHIFT, DOT11_QOS_A_MSDU_PRESENT, DOT11_QOS_CONTROL_LEN, DOT11_QOS_EOSP,
    DOT11_QOS_TID_MASK, DOT11_QOS_TID_SHIFT, DOT11_QOS_TXOP_QUEUE_SIZE_MASK,
    DOT11_QOS_TXOP_QUEUE_SIZE_SHIFT, DOT11_SEQUENCE_CONTROL_LEN,
    DOT11_SEQUENCE_FRAGMENT_NUMBER_MASK, DOT11_SEQUENCE_FRAGMENT_NUMBER_SHIFT,
    DOT11_SEQUENCE_NUMBER_MASK, DOT11_SEQUENCE_NUMBER_SHIFT, DOT11_TAG_DS_PARAMETER_SET,
    DOT11_TAG_RSN, DOT11_TAG_SSID, DOT11_TAG_SUPPORTED_RATES, DOT11_TAG_TIM,
};
// The deprecated `Icmp*` aliases (renamed to the explicit `Icmpv4*` names) are
// re-exported separately so the `#[allow(deprecated)]` exemption stays scoped to
// just these aliases.
#[allow(deprecated)]
pub use protocols::{
    Icmp, IcmpAddressMask, IcmpQuotedIpv4, IcmpRouterAdvertisementEntry, IcmpTimestamp,
};
pub use registry::{
    EthertypeBindingContext, Ipv4ProtocolBindingContext, Ipv6NextHeaderBindingContext,
    ProtocolRegistry, TcpBindingContext, UdpBindingContext,
};

pub use net::{
    default_interface, default_interface_in, default_interface_name, find_interface,
    find_interface_in, get_ip_strings, get_ips, get_my_ip, get_my_ip_in, get_my_ipv6,
    get_my_ipv6_in, get_my_mac, get_my_mac_in, interface_for, interface_for_in, interfaces,
    parse_ip_range, parse_numbers, reply_filter, reply_matches, send_packet, send_packets,
    send_plan, send_recv_packet, send_recv_packets, BatchSend, BatchSendEntry, BatchSendRecv,
    BatchSendRecvEntry, BatchSendRecvReport, BatchSendReport, InterfaceAddress, InterfaceInfo,
    Ipv4Range, NetError, PacketBatchSendExt, PacketBatchSendRecvExt, PacketSendExt,
    PacketSendRecvExt, RawSender, ReplyMatcher, SendMode, SendOptions, SendPlan, SendRecv,
    SendRecvOptions, SendRecvReport, SendReport, SendTarget, SocketSend, SocketSender,
};
pub use pcap::{
    dump_pcap, read_pcap, read_pcap_filtered, PcapError, PcapHeader, PcapLinkType, PcapPacket,
    PcapReader, PcapRecord, PcapRecords, PcapTimestamp, PcapWriter, PcapWriterOptions,
    TimestampPrecision,
};
pub use wire::Sniffer;
pub use wire::{
    derive_pmk, derive_ptk, BackendKind, BluetoothMetadata, Dot11Metadata, DropAllTransform,
    DuplicateTransform, IpDefrag, IpDefragConfig, IpDefragEvictionReason, IpDefragMetadata,
    IpDefragOverlapPolicy, IpDefragOverlapStatus, IpDefragStats, IpFragment, IpFragmentConfig,
    IpFragmentFamily, IpFragmentMetadata, IpFragmentRange, IpFragmentReason, IpFragmentStats,
    Ipv4DontFragmentPolicy, Ipv4FragmentIdentificationPolicy, Ipv6AtomicFragmentPolicy,
    Ipv6FragmentIdentificationPolicy, MediumMetadata, MemoryPacketWriter, MemoryWrite,
    OpenedPacketSource, OpenedPacketWriter, PacketMetadata, PacketOrigin, PacketRecord,
    PacketSource, PacketTransform, PacketWire, PacketWireBuilder, PacketWireTarget, PacketWriter,
    PairwiseTransientKey, PassThroughTransform, Pmk, RadioMetadata, RawSocketWireBuilder,
    RawSocketWriter, SnifferCancel, SnifferHandle, TraceAppendTransform, TransformOutput,
    TransformTrace, Transmitter, VecPacketSource, WifiDecryptState, WifiMetadata,
    WifiProtectionStatus, WireError, WpaAkm, WpaCipher, WpaCredentialStatus, WpaDecrypt,
    WpaDecryptConfig, WpaDecryptReason, WpaHandshakeStatus, WpaKeyKind, WpaMetadata, WpaNetwork,
    WriteReport, IP_DEFRAG_DEFAULT_MAX_AGE, IP_DEFRAG_DEFAULT_MAX_BYTES_PER_DATAGRAM,
    IP_DEFRAG_DEFAULT_MAX_DATAGRAMS, IP_FRAGMENT_MIN_MTU,
};

/// Core packet and protocol APIs.
pub mod core {
    pub use crate::checksum;
    pub use crate::endian;
    pub use crate::error;
    pub use crate::field;
    pub use crate::mac;
    pub use crate::packet;
    pub use crate::protocols;
    pub use crate::registry;
    pub use crate::{
        arp_hardware_type_label, arp_protocol_type_label, decode_dns_name, decode_dns_name_typed,
        decode_tftp_server_addresses, dns_type_name, eapol_descriptor_type_label, eapol_type_label,
        edns_option_code_name, hexdump, ipv6_fragment_header_status_label,
        ipv6_router_alert_value_label, ipv6_routing_type_label, ipv6_routing_type_status,
        ndp_option_type_is_known, ndp_option_type_name, ndp_rdnss_length_units, option_meta,
        option_name, option_status, rsn_akm_suite_label, rsn_cipher_suite_label,
        scan_dhcp_option_segments, svcb_param_key_name, tcp_option_kind_class,
        tcp_option_kind_is_assigned, tcp_option_kind_is_experimental, typed_option_value,
        udp_option_kind_class, udp_option_kind_is_unsafe, udp_option_kind_is_unsupported, Ah, Arp,
        ArpOperation, ClientNetworkDeviceInterface, ClientSystemArchitecture, CompiledPacket,
        CrafterError, Dhcp, DhcpAuthAlgorithm, DhcpAuthProtocol, DhcpAuthentication,
        DhcpClasslessRoute, DhcpClientIdentifier, DhcpClientUuid, DhcpDataSource,
        DhcpForcerenewNonceCapable, DhcpMalformed, DhcpMessageType, DhcpOption, DhcpOptionArea,
        DhcpOptionCode, DhcpOptionFormat, DhcpOptionKind, DhcpOptionMeta, DhcpOptionSegment,
        DhcpOptionStatus, DhcpOptionValue, DhcpRelayAgentInfo, DhcpRelaySuboption,
        DhcpRelayVendorSpecific, DhcpReplayDetectionMethod, DhcpState, DhcpStaticRoute,
        DhcpStatusCode, DhcpStatusCodeOption, DhcpUserClass, DhcpVendorClassData,
        DhcpVendorIdentifyingOption, DhcpVendorSuboption, DhcpVssInfo, Dns, DnsName, DnsQuestion,
        DnsRecord, DnsRecordData, DnsTypeBitmaps, Dot11, Dot11ActionFixedFields,
        Dot11AssociationRequestFixedFields, Dot11AssociationResponseFixedFields,
        Dot11AuthenticationFixedFields, Dot11BeaconFixedFields, Dot11ControlSubtype,
        Dot11DataSubtype, Dot11FrameControl, Dot11FrameType, Dot11ManagementFixedFields,
        Dot11ManagementSubtype, Dot11QosControl, Dot11ReasonCodeFixedFields,
        Dot11ReassociationRequestFixedFields, Dot11SequenceControl, Dot1Q, Dscp, Eapol,
        EapolDescriptorType, EapolKey, EapolKeyInformation, EapolType, Ecn, EdnsOption,
        EncryptionAlgorithm, Esp, Ethernet, EthertypeBindingContext, Field, FieldState,
        IcmpExtension, IcmpExtensionInterfaceId, IcmpExtensionInterfaceInfo, IcmpExtensionMpls,
        IcmpExtensionObject, IcmpInterfaceIpAddress, IcmpKind, IcmpLayer, Icmpv4,
        Icmpv4AddressMask, Icmpv4QuotedIp, Icmpv4RouterAdvertisementEntry, Icmpv4Timestamp, Icmpv6,
        Icmpv6Body, Icmpv6ErrorBody, IntegrityAlgorithm, IntoPacket, IpsecMode, Ipv4,
        Ipv4ChecksumStatus, Ipv4FragmentInfo, Ipv4Option, Ipv4OptionIter, Ipv4OptionKind,
        Ipv4Protocol, Ipv4ProtocolBindingContext, Ipv4RouteOptionKind, Ipv6,
        Ipv6DestinationOptionsHeader, Ipv6FragmentHeader, Ipv6FragmentHeaderStatus,
        Ipv6HopByHopOptionsHeader, Ipv6MobileRoutingHeader, Ipv6MobileRoutingHeaderStatus,
        Ipv6NextHeaderBindingContext, Ipv6Option, Ipv6OptionAction, Ipv6OptionIter,
        Ipv6RoutingHeader, Ipv6RoutingTypeStatus, Ipv6SegmentRoutingHeader, Layer, LayerContext,
        LinkType, LinuxSll, LlcSnap, MacAddr, Mldv2Query, Mldv2Report, MulticastAddressRecord,
        MulticastListenerMessage, MulticastRecordType, NdpOption, NdpOptions,
        NeighborAdvertisement, NeighborSolicitation, NetworkLayer, NodeInformation, NullByteOrder,
        NullLoopback, OptionOverload, Packet, Pref64Plc, Prf, ProtocolRegistry, Radiotap, Raw,
        Redirect, Result, RouterAdvertisement, RouterSolicitation, RsnAkmSuite, RsnCapabilities,
        RsnCipherSuite, RsnEapolKeyHandshakeMessage, RsnEapolKeyHandshakeMetadata, RsnInformation,
        RsnSuiteSelector, SecurityAssociation, SipServers, SvcParam, SvcParams, Tcp,
        TcpBindingContext, TcpExtendedDataOffset, TcpOption, TcpOptionIter, TcpOptionKindClass,
        TcpSackBlock, TransportChecksumContext, Udp, UdpBindingContext, UdpChecksumStatus,
        UdpOption, UdpOptionIter, UdpOptionKindClass, UdpOptionStatus, UdpOptions, Vlan,
        AH_FIXED_LEN, AH_HIGH_SEQUENCE_LEN, AH_LENGTH_UNIT, AH_NEXT_HEADER_LEN,
        AH_PAYLOAD_LEN_FIELD_LEN, AH_PAYLOAD_LEN_OFFSET, AH_RESERVED_LEN, AH_SEQUENCE_LEN,
        AH_SPI_LEN, ARP_HRD_ATM, ARP_HRD_ETHERNET, ARP_HRD_FIBRE_CHANNEL, ARP_HRD_IEEE_802,
        ARP_HRD_INFINIBAND, ARP_HRD_MAPOS, ARP_OP_ARP_NAK, ARP_OP_DRARP_ERROR, ARP_OP_DRARP_REPLY,
        ARP_OP_DRARP_REQUEST, ARP_OP_EXP1, ARP_OP_EXP2, ARP_OP_INARP_REPLY, ARP_OP_INARP_REQUEST,
        ARP_OP_MAPOS_UNARP, ARP_OP_RARP_REPLY, ARP_OP_RARP_REQUEST, ARP_OP_REPLY, ARP_OP_REQUEST,
        ARP_OP_RESERVED, ARP_OP_RESERVED_MAX, ARP_PRO_IPV4, BOOTP_REPLY, BOOTP_REQUEST, DHCP_ACK,
        DHCP_CLIENT_PORT, DHCP_DECLINE, DHCP_DISCOVER, DHCP_HTYPE_ETHERNET, DHCP_INFORM,
        DHCP_MAGIC_COOKIE, DHCP_MAGIC_COOKIE_LEN, DHCP_MIN_LEN, DHCP_NAK, DHCP_OFFER,
        DHCP_OPTION_BROADCAST_ADDRESS, DHCP_OPTION_CLIENT_IDENTIFIER, DHCP_OPTION_DOMAIN_NAME,
        DHCP_OPTION_DOMAIN_NAME_SERVER, DHCP_OPTION_END, DHCP_OPTION_HOST_NAME,
        DHCP_OPTION_IP_ADDRESS_LEASE_TIME, DHCP_OPTION_MESSAGE_TYPE, DHCP_OPTION_OVERLOAD,
        DHCP_OPTION_PAD, DHCP_OPTION_PARAMETER_REQUEST_LIST, DHCP_OPTION_PRIVATE_USE_END,
        DHCP_OPTION_PRIVATE_USE_START, DHCP_OPTION_REBINDING_TIME,
        DHCP_OPTION_RELAY_AGENT_INFORMATION, DHCP_OPTION_RENEWAL_TIME,
        DHCP_OPTION_REQUESTED_IP_ADDRESS, DHCP_OPTION_ROUTER, DHCP_OPTION_SERVER_IDENTIFIER,
        DHCP_OPTION_SUBNET_MASK, DHCP_OVERLOAD_BOTH, DHCP_OVERLOAD_FILE, DHCP_OVERLOAD_SNAME,
        DHCP_RELAY_FLAG_UNICAST, DHCP_RELAY_SUBOPTION_ACCESS_NETWORK_NAME,
        DHCP_RELAY_SUBOPTION_ACCESS_POINT_BSSID, DHCP_RELAY_SUBOPTION_ACCESS_POINT_NAME,
        DHCP_RELAY_SUBOPTION_ACCESS_TECHNOLOGY_TYPE, DHCP_RELAY_SUBOPTION_AUTHENTICATION,
        DHCP_RELAY_SUBOPTION_CIRCUIT_ID, DHCP_RELAY_SUBOPTION_DOCSIS_DEVICE_CLASS,
        DHCP_RELAY_SUBOPTION_LINK_SELECTION, DHCP_RELAY_SUBOPTION_OPERATOR_IDENTIFIER,
        DHCP_RELAY_SUBOPTION_OPERATOR_REALM, DHCP_RELAY_SUBOPTION_RADIUS_ATTRIBUTES,
        DHCP_RELAY_SUBOPTION_RELAY_AGENT_ID, DHCP_RELAY_SUBOPTION_RELAY_FLAGS,
        DHCP_RELAY_SUBOPTION_RELAY_SOURCE_PORT, DHCP_RELAY_SUBOPTION_REMOTE_ID,
        DHCP_RELAY_SUBOPTION_SERVER_ID_OVERRIDE, DHCP_RELAY_SUBOPTION_SUBSCRIBER_ID,
        DHCP_RELAY_SUBOPTION_VENDOR_SPECIFIC, DHCP_RELAY_SUBOPTION_VSS,
        DHCP_RELAY_SUBOPTION_VSS_CONTROL, DHCP_RELEASE, DHCP_REQUEST, DHCP_SERVER_PORT,
        DHCP_VSS_TYPE_GLOBAL_DEFAULT, DHCP_VSS_TYPE_NVT_ASCII, DHCP_VSS_TYPE_VPN_ID, DNS_CLASS_ANY,
        DNS_CLASS_CH, DNS_CLASS_HS, DNS_CLASS_IN, DNS_CLASS_NONE,
        DNS_EDNS_DEFAULT_UDP_PAYLOAD_SIZE, DNS_EDNS_FLAG_DO, DNS_EDNS_OPTION_CLIENT_SUBNET,
        DNS_EDNS_OPTION_COOKIE, DNS_EDNS_OPTION_DAU, DNS_EDNS_OPTION_DHU, DNS_EDNS_OPTION_EXPIRE,
        DNS_EDNS_OPTION_EXTENDED_ERROR, DNS_EDNS_OPTION_N3U, DNS_EDNS_OPTION_NSID,
        DNS_EDNS_OPTION_PADDING, DNS_EDNS_OPTION_TCP_KEEPALIVE, DNS_FLAG_AUTHENTIC_DATA,
        DNS_FLAG_AUTHORITATIVE, DNS_FLAG_CHECKING_DISABLED, DNS_FLAG_QR_RESPONSE,
        DNS_FLAG_RECURSION_AVAILABLE, DNS_FLAG_RECURSION_DESIRED, DNS_FLAG_TRUNCATED,
        DNS_HEADER_LEN, DNS_OPCODE_DSO, DNS_OPCODE_IQUERY, DNS_OPCODE_NOTIFY, DNS_OPCODE_QUERY,
        DNS_OPCODE_STATUS, DNS_OPCODE_UPDATE, DNS_PORT, DNS_RCODE_DSOTYPENI, DNS_RCODE_FORMERR,
        DNS_RCODE_NOERROR, DNS_RCODE_NOTAUTH, DNS_RCODE_NOTIMP, DNS_RCODE_NOTZONE,
        DNS_RCODE_NXDOMAIN, DNS_RCODE_NXRRSET, DNS_RCODE_REFUSED, DNS_RCODE_SERVFAIL,
        DNS_RCODE_YXDOMAIN, DNS_RCODE_YXRRSET, DNS_SVCB_KEY_ALPN, DNS_SVCB_KEY_DOHPATH,
        DNS_SVCB_KEY_ECH, DNS_SVCB_KEY_IPV4HINT, DNS_SVCB_KEY_IPV6HINT, DNS_SVCB_KEY_MANDATORY,
        DNS_SVCB_KEY_NO_DEFAULT_ALPN, DNS_SVCB_KEY_PORT, DNS_TYPE_A, DNS_TYPE_AAAA, DNS_TYPE_CNAME,
        DNS_TYPE_DNSKEY, DNS_TYPE_DS, DNS_TYPE_HTTPS, DNS_TYPE_MX, DNS_TYPE_NS, DNS_TYPE_NSEC,
        DNS_TYPE_NSEC3, DNS_TYPE_NSEC3PARAM, DNS_TYPE_OPT, DNS_TYPE_PTR, DNS_TYPE_RRSIG,
        DNS_TYPE_SOA, DNS_TYPE_SRV, DNS_TYPE_SVCB, DNS_TYPE_TLSA, DNS_TYPE_TXT, EAPOL_HEADER_LEN,
        EAPOL_KEY_DESCRIPTOR_MIN_LEN, EAPOL_KEY_DESCRIPTOR_RSN, EAPOL_TYPE_ASF_ALERT,
        EAPOL_TYPE_EAP_PACKET, EAPOL_TYPE_KEY, EAPOL_TYPE_LOGOFF, EAPOL_TYPE_START,
        EAPOL_VERSION_1, EAPOL_VERSION_2, EAPOL_VERSION_3, ESP_HEADER_LEN, ESP_HIGH_SEQUENCE_LEN,
        ESP_MAX_PAD_LEN, ESP_NEXT_HEADER_FIELD_LEN, ESP_PAD_LENGTH_FIELD_LEN, ETHERTYPE_ARP,
        ETHERTYPE_EAPOL, ETHERTYPE_IPV4, ETHERTYPE_IPV6, ETHERTYPE_VLAN,
        ICMPV6_CODE_EXTENDED_ECHO_REPLY_MALFORMED_QUERY,
        ICMPV6_CODE_EXTENDED_ECHO_REPLY_MULTIPLE_INTERFACES,
        ICMPV6_CODE_EXTENDED_ECHO_REPLY_NO_ERROR,
        ICMPV6_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_INTERFACE,
        ICMPV6_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_TABLE_ENTRY, ICMPV6_DESTINATION_UNREACHABLE,
        ICMPV6_ECHO_REPLY, ICMPV6_ECHO_REQUEST, ICMPV6_EXTENDED_ECHO_REPLY,
        ICMPV6_EXTENDED_ECHO_REPLY_ACTIVE, ICMPV6_EXTENDED_ECHO_REPLY_IPV4,
        ICMPV6_EXTENDED_ECHO_REPLY_IPV6, ICMPV6_EXTENDED_ECHO_REPLY_STATE_DELAY,
        ICMPV6_EXTENDED_ECHO_REPLY_STATE_FAILED, ICMPV6_EXTENDED_ECHO_REPLY_STATE_INCOMPLETE,
        ICMPV6_EXTENDED_ECHO_REPLY_STATE_PROBE, ICMPV6_EXTENDED_ECHO_REPLY_STATE_REACHABLE,
        ICMPV6_EXTENDED_ECHO_REPLY_STATE_RESERVED, ICMPV6_EXTENDED_ECHO_REPLY_STATE_STALE,
        ICMPV6_EXTENDED_ECHO_REQUEST, ICMPV6_EXTENDED_ECHO_REQUEST_L_BIT,
        ICMPV6_INVERSE_ND_ADVERTISEMENT, ICMPV6_INVERSE_ND_SOLICITATION, ICMPV6_MLDV2_REPORT,
        ICMPV6_MULTICAST_LISTENER_DONE, ICMPV6_MULTICAST_LISTENER_QUERY,
        ICMPV6_MULTICAST_LISTENER_REPORT, ICMPV6_NA_FLAGS_RESERVED, ICMPV6_NA_FLAG_OVERRIDE,
        ICMPV6_NA_FLAG_ROUTER, ICMPV6_NA_FLAG_SOLICITED, ICMPV6_NEIGHBOR_ADVERTISEMENT,
        ICMPV6_NEIGHBOR_SOLICITATION, ICMPV6_NODE_INFORMATION_QUERY,
        ICMPV6_NODE_INFORMATION_RESPONSE, ICMPV6_PACKET_TOO_BIG, ICMPV6_PARAMETER_PROBLEM,
        ICMPV6_RA_DEFAULT_CUR_HOP_LIMIT, ICMPV6_RA_DEFAULT_ROUTER_LIFETIME,
        ICMPV6_RA_FLAGS_RESERVED, ICMPV6_RA_FLAG_MANAGED, ICMPV6_RA_FLAG_OTHER, ICMPV6_REDIRECT,
        ICMPV6_ROUTER_ADVERTISEMENT, ICMPV6_ROUTER_RENUMBERING, ICMPV6_ROUTER_SOLICITATION,
        ICMPV6_TIME_EXCEEDED, ICMP_ADDRESS_MASK_REPLY, ICMP_ADDRESS_MASK_REQUEST,
        ICMP_ALTERNATE_HOST_ADDRESS, ICMP_CODE_DU_COMM_ADMIN_PROHIBITED,
        ICMP_CODE_DU_DEST_HOST_UNKNOWN, ICMP_CODE_DU_DEST_NETWORK_UNKNOWN,
        ICMP_CODE_DU_FRAGMENTATION_NEEDED, ICMP_CODE_DU_HOST_ADMIN_PROHIBITED,
        ICMP_CODE_DU_HOST_PRECEDENCE_VIOLATION, ICMP_CODE_DU_HOST_UNREACHABLE,
        ICMP_CODE_DU_HOST_UNREACHABLE_TOS, ICMP_CODE_DU_NETWORK_ADMIN_PROHIBITED,
        ICMP_CODE_DU_NETWORK_UNREACHABLE_TOS, ICMP_CODE_DU_NET_UNREACHABLE,
        ICMP_CODE_DU_PORT_UNREACHABLE, ICMP_CODE_DU_PRECEDENCE_CUTOFF,
        ICMP_CODE_DU_PROTOCOL_UNREACHABLE, ICMP_CODE_DU_SOURCE_HOST_ISOLATED,
        ICMP_CODE_DU_SOURCE_ROUTE_FAILED, ICMP_CODE_EXTENDED_ECHO_REPLY_MALFORMED_QUERY,
        ICMP_CODE_EXTENDED_ECHO_REPLY_MULTIPLE_INTERFACES, ICMP_CODE_EXTENDED_ECHO_REPLY_NO_ERROR,
        ICMP_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_INTERFACE,
        ICMP_CODE_EXTENDED_ECHO_REPLY_NO_SUCH_TABLE_ENTRY, ICMP_CODE_PARAMETER_PROBLEM_BAD_LENGTH,
        ICMP_CODE_PARAMETER_PROBLEM_MISSING_OPTION, ICMP_CODE_PARAMETER_PROBLEM_POINTER,
        ICMP_CODE_PHOTURIS_AUTHENTICATION_FAILED, ICMP_CODE_PHOTURIS_BAD_SPI,
        ICMP_CODE_PHOTURIS_DECOMPRESSION_FAILED, ICMP_CODE_PHOTURIS_DECRYPTION_FAILED,
        ICMP_CODE_PHOTURIS_NEED_AUTHENTICATION, ICMP_CODE_PHOTURIS_NEED_AUTHORIZATION,
        ICMP_CODE_REDIRECT_HOST, ICMP_CODE_REDIRECT_NETWORK, ICMP_CODE_REDIRECT_TOS_HOST,
        ICMP_CODE_REDIRECT_TOS_NETWORK, ICMP_CODE_ROUTER_ADVERTISEMENT_NORMAL,
        ICMP_CODE_ROUTER_ADVERTISEMENT_NO_COMMON_TRAFFIC,
        ICMP_CODE_TIME_EXCEEDED_FRAGMENT_REASSEMBLY, ICMP_CODE_TIME_EXCEEDED_TTL,
        ICMP_DATAGRAM_CONVERSION_ERROR, ICMP_DESTINATION_UNREACHABLE, ICMP_DOMAIN_NAME_REPLY,
        ICMP_DOMAIN_NAME_REQUEST, ICMP_ECHO_REPLY, ICMP_ECHO_REQUEST, ICMP_EXPERIMENTAL_253,
        ICMP_EXPERIMENTAL_254, ICMP_EXTENDED_ECHO_REPLY, ICMP_EXTENDED_ECHO_REPLY_ACTIVE,
        ICMP_EXTENDED_ECHO_REPLY_IPV4, ICMP_EXTENDED_ECHO_REPLY_IPV6,
        ICMP_EXTENDED_ECHO_REPLY_STATE_DELAY, ICMP_EXTENDED_ECHO_REPLY_STATE_FAILED,
        ICMP_EXTENDED_ECHO_REPLY_STATE_INCOMPLETE, ICMP_EXTENDED_ECHO_REPLY_STATE_PROBE,
        ICMP_EXTENDED_ECHO_REPLY_STATE_REACHABLE, ICMP_EXTENDED_ECHO_REPLY_STATE_RESERVED,
        ICMP_EXTENDED_ECHO_REPLY_STATE_STALE, ICMP_EXTENDED_ECHO_REQUEST,
        ICMP_EXTENDED_ECHO_REQUEST_L_BIT, ICMP_EXTENSION_CLASS_INTERFACE_ID,
        ICMP_EXTENSION_CLASS_INTERFACE_INFO, ICMP_EXTENSION_CLASS_MPLS,
        ICMP_EXTENSION_CTYPE_MPLS_INCOMING, ICMP_INFORMATION_REPLY, ICMP_INFORMATION_REQUEST,
        ICMP_INTERFACE_AFI_IPV4, ICMP_INTERFACE_AFI_IPV6, ICMP_INTERFACE_CTYPE_IFINDEX,
        ICMP_INTERFACE_CTYPE_IP_ADDRESS, ICMP_INTERFACE_CTYPE_MTU, ICMP_INTERFACE_CTYPE_NAME,
        ICMP_INTERFACE_ID_CTYPE_ADDRESS, ICMP_INTERFACE_ID_CTYPE_INDEX,
        ICMP_INTERFACE_ID_CTYPE_NAME, ICMP_INTERFACE_ROLE_INCOMING, ICMP_INTERFACE_ROLE_NEXT_HOP,
        ICMP_INTERFACE_ROLE_OUTGOING, ICMP_INTERFACE_ROLE_SUB_IP_INCOMING, ICMP_IPV6_I_AM_HERE,
        ICMP_IPV6_WHERE_ARE_YOU, ICMP_MOBILE_HOST_REDIRECT, ICMP_MOBILE_REGISTRATION_REPLY,
        ICMP_MOBILE_REGISTRATION_REQUEST, ICMP_PARAMETER_PROBLEM, ICMP_PHOTURIS, ICMP_REDIRECT,
        ICMP_RESERVED_255, ICMP_RESERVED_ROBUSTNESS_EXPERIMENT_FIRST,
        ICMP_RESERVED_ROBUSTNESS_EXPERIMENT_LAST, ICMP_RESERVED_SECURITY,
        ICMP_ROUTER_ADVERTISEMENT, ICMP_ROUTER_ADVERTISEMENT_ENTRY_WORDS, ICMP_ROUTER_SOLICITATION,
        ICMP_SEAMOBY_EXPERIMENTAL, ICMP_SKIP, ICMP_SOURCE_QUENCH, ICMP_TIMESTAMP,
        ICMP_TIMESTAMP_REPLY, ICMP_TIME_EXCEEDED, ICMP_TRACEROUTE, IPPROTO_AH, IPPROTO_ESP,
        IPPROTO_EXPERIMENTAL_1, IPPROTO_EXPERIMENTAL_2, IPPROTO_GRE, IPPROTO_ICMP, IPPROTO_ICMPV6,
        IPPROTO_IPV6, IPPROTO_IPV6_AH, IPPROTO_IPV6_DSTOPTS, IPPROTO_IPV6_ESP,
        IPPROTO_IPV6_EXPERIMENTAL_1, IPPROTO_IPV6_EXPERIMENTAL_2, IPPROTO_IPV6_FRAGMENT,
        IPPROTO_IPV6_HIP, IPPROTO_IPV6_HOPOPTS, IPPROTO_IPV6_MOBILITY, IPPROTO_IPV6_NO_NEXT,
        IPPROTO_IPV6_ROUTE, IPPROTO_IPV6_SHIM6, IPPROTO_OSPF, IPPROTO_SCTP, IPPROTO_TCP,
        IPPROTO_UDP, IPV4_FLAG_DONT_FRAGMENT, IPV4_FLAG_MORE_FRAGMENTS, IPV4_FLAG_RESERVED,
        IPV4_OPTION_EOL, IPV4_OPTION_EXPERIMENTAL_1, IPV4_OPTION_EXPERIMENTAL_2,
        IPV4_OPTION_EXPERIMENTAL_3, IPV4_OPTION_EXPERIMENTAL_4, IPV4_OPTION_LOOSE_SOURCE_ROUTE,
        IPV4_OPTION_NOP, IPV4_OPTION_RECORD_ROUTE, IPV4_OPTION_ROUTER_ALERT,
        IPV4_OPTION_STRICT_SOURCE_ROUTE, IPV4_OPTION_TIMESTAMP, IPV4_OPTION_TRACEROUTE,
        IPV6_MOBILE_ROUTING_HEADER_EXT_LEN, IPV6_MOBILE_ROUTING_RESERVED,
        IPV6_MOBILE_ROUTING_SEGMENTS_LEFT, IPV6_OPTION_HOME_ADDRESS, IPV6_OPTION_JUMBO_PAYLOAD,
        IPV6_OPTION_PAD1, IPV6_OPTION_PADN, IPV6_OPTION_ROUTER_ALERT,
        IPV6_ROUTER_ALERT_ACTIVE_NETWORKS, IPV6_ROUTER_ALERT_MLD, IPV6_ROUTER_ALERT_MPLS_OAM,
        IPV6_ROUTER_ALERT_RESERVED, IPV6_ROUTER_ALERT_RSVP, IPV6_ROUTING_TYPE_CRH16,
        IPV6_ROUTING_TYPE_CRH32, IPV6_ROUTING_TYPE_EXPERIMENTAL_1,
        IPV6_ROUTING_TYPE_EXPERIMENTAL_2, IPV6_ROUTING_TYPE_MOBILE, IPV6_ROUTING_TYPE_NIMROD,
        IPV6_ROUTING_TYPE_RESERVED, IPV6_ROUTING_TYPE_RH0, IPV6_ROUTING_TYPE_RPL,
        IPV6_ROUTING_TYPE_SEGMENT, IPV6_ROUTING_TYPE_SOURCE_ROUTE, IPV6_SEGMENT_POLICY_EGRESS,
        IPV6_SEGMENT_POLICY_INGRESS, IPV6_SEGMENT_POLICY_SOURCE_ADDRESS, IPV6_SEGMENT_POLICY_UNSET,
        MLDV2_QUERY_MIN_BODY_LEN, MLDV2_QUERY_QRV_MASK, MLDV2_QUERY_RESV_MASK, MLDV2_QUERY_S_FLAG,
        NDP_DNS_LIFETIME_INFINITY, NDP_DNS_RESERVED_LEN, NDP_LINK_LAYER_ADDR_ETHERNET_LEN,
        NDP_MTU_OPTION_LEN, NDP_MTU_OPTION_UNITS, NDP_NONCE_MIN_LEN, NDP_OPTION_HEADER_LEN,
        NDP_OPTION_LENGTH_UNIT, NDP_OPT_CAPTIVE_PORTAL, NDP_OPT_DNSSL, NDP_OPT_MTU, NDP_OPT_NONCE,
        NDP_OPT_PREF64, NDP_OPT_PREFIX_INFORMATION, NDP_OPT_RA_FLAGS_EXTENSION, NDP_OPT_RDNSS,
        NDP_OPT_REDIRECTED_HEADER, NDP_OPT_ROUTE_INFORMATION, NDP_OPT_SOURCE_LINK_LAYER_ADDR,
        NDP_OPT_TARGET_LINK_LAYER_ADDR, NDP_PREF64_LEN, NDP_PREF64_PLC_MASK, NDP_PREF64_PREFIX_LEN,
        NDP_PREF64_SCALED_LIFETIME_MAX, NDP_PREF64_SCALED_LIFETIME_SHIFT, NDP_PREF64_UNITS,
        NDP_PREFIX_FLAGS_RESERVED, NDP_PREFIX_FLAG_AUTONOMOUS, NDP_PREFIX_FLAG_ON_LINK,
        NDP_PREFIX_INFORMATION_LEN, NDP_PREFIX_INFORMATION_UNITS, NDP_PREFIX_LIFETIME_INFINITY,
        NDP_PRF_MASK, NDP_PRF_SHIFT, NDP_RA_FLAGS_EXTENSION_BITS_LEN, NDP_RA_FLAGS_EXTENSION_LEN,
        NDP_RA_FLAGS_EXTENSION_UNITS, NDP_RDNSS_ADDRESS_LEN, NDP_REDIRECTED_HEADER_RESERVED_LEN,
        NDP_ROUTE_INFORMATION_LEN_FULL_PREFIX, NDP_ROUTE_INFORMATION_LEN_HALF_PREFIX,
        NDP_ROUTE_INFORMATION_LEN_NO_PREFIX, NDP_ROUTE_LIFETIME_INFINITY, NI_NONCE_LEN,
        NI_QTYPE_IPV4_ADDRESSES, NI_QTYPE_NODE_ADDRESSES, NI_QTYPE_NODE_NAME, NI_QTYPE_NOOP,
        NI_QUERY_CODE_SUBJECT_IPV4, NI_QUERY_CODE_SUBJECT_IPV6, NI_QUERY_CODE_SUBJECT_NAME,
        NI_RESPONSE_CODE_REFUSED, NI_RESPONSE_CODE_SUCCESS, NI_RESPONSE_CODE_UNKNOWN_QTYPE,
        RSN_AKM_SUITE_8021X, RSN_AKM_SUITE_8021X_SHA256, RSN_AKM_SUITE_8021X_SUITE_B,
        RSN_AKM_SUITE_8021X_SUITE_B_192, RSN_AKM_SUITE_AP_PEER_KEY, RSN_AKM_SUITE_EDPKE,
        RSN_AKM_SUITE_FILS_SHA256, RSN_AKM_SUITE_FILS_SHA384, RSN_AKM_SUITE_FT_8021X,
        RSN_AKM_SUITE_FT_8021X_SHA384, RSN_AKM_SUITE_FT_8021X_SHA384_BASIC,
        RSN_AKM_SUITE_FT_8021X_SHA384_CMP_256, RSN_AKM_SUITE_FT_FILS_SHA256,
        RSN_AKM_SUITE_FT_FILS_SHA384, RSN_AKM_SUITE_FT_PSK, RSN_AKM_SUITE_FT_PSK_SHA384,
        RSN_AKM_SUITE_FT_SAE, RSN_AKM_SUITE_FT_SAE_PMK384, RSN_AKM_SUITE_OWE, RSN_AKM_SUITE_PASN,
        RSN_AKM_SUITE_PASN_DEFINED_KEY_WRAP, RSN_AKM_SUITE_PSK, RSN_AKM_SUITE_PSK_SHA256,
        RSN_AKM_SUITE_PSK_SHA384, RSN_AKM_SUITE_SAE, RSN_AKM_SUITE_SAE_PMK384, RSN_AKM_SUITE_TDLS,
        RSN_CAPABILITIES_LEN, RSN_CIPHER_SUITE_AES_128_CMAC, RSN_CIPHER_SUITE_BIP_CMAC_256,
        RSN_CIPHER_SUITE_BIP_GMAC_128, RSN_CIPHER_SUITE_BIP_GMAC_256, RSN_CIPHER_SUITE_CCMP_128,
        RSN_CIPHER_SUITE_CCMP_256, RSN_CIPHER_SUITE_CCM_STAR, RSN_CIPHER_SUITE_GCMP_128,
        RSN_CIPHER_SUITE_GCMP_256, RSN_CIPHER_SUITE_NO_GROUP_ADDRESSED, RSN_CIPHER_SUITE_TKIP,
        RSN_CIPHER_SUITE_USE_GROUP, RSN_SUITE_SELECTOR_LEN, RSN_SUITE_SELECTOR_OUI, RSN_VERSION_1,
        TCP_EDO_HEADER_AND_SEGMENT_LEN, TCP_EDO_HEADER_LEN, TCP_EDO_REQUEST_LEN, TCP_FLAG_ACK,
        TCP_FLAG_AE, TCP_FLAG_CWR, TCP_FLAG_ECE, TCP_FLAG_FIN, TCP_FLAG_NS, TCP_FLAG_PSH,
        TCP_FLAG_RST, TCP_FLAG_SYN, TCP_FLAG_URG, TCP_OPTION_EDO, TCP_OPTION_EOL,
        TCP_OPTION_FAST_OPEN, TCP_OPTION_MPTCP, TCP_OPTION_MSS, TCP_OPTION_NOP, TCP_OPTION_SACK,
        TCP_OPTION_SACK_PERMITTED, TCP_OPTION_TIMESTAMP, TCP_OPTION_WINDOW_SCALE, UDP_HEADER_LEN,
        UDP_OPTION_APC, UDP_OPTION_AUTH, UDP_OPTION_EOL, UDP_OPTION_EXP, UDP_OPTION_FRAG,
        UDP_OPTION_MDS, UDP_OPTION_MRDS, UDP_OPTION_NOP, UDP_OPTION_REQ, UDP_OPTION_RES,
        UDP_OPTION_RESERVED_SAFE_END, UDP_OPTION_RESERVED_SAFE_START, UDP_OPTION_RESERVED_UNSAFE,
        UDP_OPTION_TIME, UDP_OPTION_UCMP, UDP_OPTION_UENC, UDP_OPTION_UEXP,
        UDP_OPTION_UNASSIGNED_SAFE_END, UDP_OPTION_UNASSIGNED_SAFE_START,
        UDP_OPTION_UNASSIGNED_UNSAFE_END, UDP_OPTION_UNASSIGNED_UNSAFE_START,
    };
    pub use crate::{
        dot11_category_label, dot11_control_subtype_label, dot11_data_subtype_label,
        dot11_frame_type_label, dot11_management_subtype_label, dot11_subtype_label,
        Dot11TaggedParameter, DOT11_ADDRESS_LEN, DOT11_CAPABILITY_APSD,
        DOT11_CAPABILITY_CF_POLLABLE, DOT11_CAPABILITY_CF_POLL_REQUEST,
        DOT11_CAPABILITY_CHANNEL_AGILITY, DOT11_CAPABILITY_DELAYED_BLOCK_ACK,
        DOT11_CAPABILITY_DSSS_OFDM, DOT11_CAPABILITY_ESS, DOT11_CAPABILITY_IBSS,
        DOT11_CAPABILITY_IMMEDIATE_BLOCK_ACK, DOT11_CAPABILITY_PBCC, DOT11_CAPABILITY_PRIVACY,
        DOT11_CAPABILITY_QOS, DOT11_CAPABILITY_RADIO_MEASUREMENT, DOT11_CAPABILITY_SHORT_PREAMBLE,
        DOT11_CAPABILITY_SHORT_SLOT_TIME, DOT11_CAPABILITY_SPECTRUM_MANAGEMENT,
        DOT11_CATEGORY_BLOCK_ACK, DOT11_CATEGORY_DLS, DOT11_CATEGORY_FAST_BSS_TRANSITION,
        DOT11_CATEGORY_HT, DOT11_CATEGORY_MESH, DOT11_CATEGORY_MULTIHOP,
        DOT11_CATEGORY_PROTECTED_DUAL_OF_PUBLIC_ACTION, DOT11_CATEGORY_PUBLIC, DOT11_CATEGORY_QOS,
        DOT11_CATEGORY_RADIO_MEASUREMENT, DOT11_CATEGORY_SA_QUERY, DOT11_CATEGORY_SELF_PROTECTED,
        DOT11_CATEGORY_SPECTRUM_MANAGEMENT, DOT11_CATEGORY_TDLS, DOT11_CATEGORY_UNPROTECTED_WNM,
        DOT11_CATEGORY_WNM, DOT11_CONTROL_ONE_ADDRESS_HEADER_LEN, DOT11_CONTROL_SUBTYPE_ACK,
        DOT11_CONTROL_SUBTYPE_BLOCK_ACK, DOT11_CONTROL_SUBTYPE_BLOCK_ACK_REQUEST,
        DOT11_CONTROL_SUBTYPE_CF_END, DOT11_CONTROL_SUBTYPE_CF_END_CF_ACK,
        DOT11_CONTROL_SUBTYPE_CONTROL_WRAPPER, DOT11_CONTROL_SUBTYPE_CTS,
        DOT11_CONTROL_SUBTYPE_PS_POLL, DOT11_CONTROL_SUBTYPE_RTS, DOT11_CONTROL_SUBTYPE_TRIGGER,
        DOT11_CONTROL_TWO_ADDRESS_HEADER_LEN, DOT11_DATA_ADDR4_HEADER_LEN, DOT11_DATA_HEADER_LEN,
        DOT11_DATA_SUBTYPE_CF_ACK, DOT11_DATA_SUBTYPE_CF_ACK_CF_POLL, DOT11_DATA_SUBTYPE_CF_POLL,
        DOT11_DATA_SUBTYPE_DATA, DOT11_DATA_SUBTYPE_DATA_CF_ACK,
        DOT11_DATA_SUBTYPE_DATA_CF_ACK_CF_POLL, DOT11_DATA_SUBTYPE_DATA_CF_POLL,
        DOT11_DATA_SUBTYPE_NULL, DOT11_DATA_SUBTYPE_QOS_CF_ACK_CF_POLL,
        DOT11_DATA_SUBTYPE_QOS_CF_POLL, DOT11_DATA_SUBTYPE_QOS_DATA,
        DOT11_DATA_SUBTYPE_QOS_DATA_CF_ACK, DOT11_DATA_SUBTYPE_QOS_DATA_CF_ACK_CF_POLL,
        DOT11_DATA_SUBTYPE_QOS_DATA_CF_POLL, DOT11_DATA_SUBTYPE_QOS_NULL, DOT11_DURATION_ID_LEN,
        DOT11_FC_FROM_DS, DOT11_FC_MORE_DATA, DOT11_FC_MORE_FRAGMENTS, DOT11_FC_ORDER,
        DOT11_FC_POWER_MANAGEMENT, DOT11_FC_PROTECTED, DOT11_FC_PROTOCOL_VERSION_MASK,
        DOT11_FC_PROTOCOL_VERSION_SHIFT, DOT11_FC_RETRY, DOT11_FC_SUBTYPE_MASK,
        DOT11_FC_SUBTYPE_SHIFT, DOT11_FC_TO_DS, DOT11_FC_TYPE_MASK, DOT11_FC_TYPE_SHIFT,
        DOT11_FRAME_CONTROL_LEN, DOT11_FRAME_TYPE_CONTROL, DOT11_FRAME_TYPE_DATA,
        DOT11_FRAME_TYPE_EXTENSION, DOT11_FRAME_TYPE_MANAGEMENT, DOT11_HT_CONTROL_LEN,
        DOT11_MGMT_ACTION_FIXED_LEN, DOT11_MGMT_ASSOCIATION_REQUEST_FIXED_LEN,
        DOT11_MGMT_ASSOCIATION_RESPONSE_FIXED_LEN, DOT11_MGMT_AUTHENTICATION_FIXED_LEN,
        DOT11_MGMT_BEACON_FIXED_LEN, DOT11_MGMT_DEAUTHENTICATION_FIXED_LEN,
        DOT11_MGMT_DISASSOCIATION_FIXED_LEN, DOT11_MGMT_PROBE_RESPONSE_FIXED_LEN,
        DOT11_MGMT_REASSOCIATION_REQUEST_FIXED_LEN, DOT11_MGMT_REASSOCIATION_RESPONSE_FIXED_LEN,
        DOT11_MGMT_SUBTYPE_ACTION, DOT11_MGMT_SUBTYPE_ACTION_NO_ACK,
        DOT11_MGMT_SUBTYPE_ASSOCIATION_REQUEST, DOT11_MGMT_SUBTYPE_ASSOCIATION_RESPONSE,
        DOT11_MGMT_SUBTYPE_ATIM, DOT11_MGMT_SUBTYPE_AUTHENTICATION, DOT11_MGMT_SUBTYPE_BEACON,
        DOT11_MGMT_SUBTYPE_DEAUTHENTICATION, DOT11_MGMT_SUBTYPE_DISASSOCIATION,
        DOT11_MGMT_SUBTYPE_PROBE_REQUEST, DOT11_MGMT_SUBTYPE_PROBE_RESPONSE,
        DOT11_MGMT_SUBTYPE_REASSOCIATION_REQUEST, DOT11_MGMT_SUBTYPE_REASSOCIATION_RESPONSE,
        DOT11_MGMT_SUBTYPE_TIMING_ADVERTISEMENT, DOT11_MIN_HEADER_LEN, DOT11_QOS_ACK_POLICY_MASK,
        DOT11_QOS_ACK_POLICY_SHIFT, DOT11_QOS_A_MSDU_PRESENT, DOT11_QOS_CONTROL_LEN,
        DOT11_QOS_EOSP, DOT11_QOS_TID_MASK, DOT11_QOS_TID_SHIFT, DOT11_QOS_TXOP_QUEUE_SIZE_MASK,
        DOT11_QOS_TXOP_QUEUE_SIZE_SHIFT, DOT11_SEQUENCE_CONTROL_LEN,
        DOT11_SEQUENCE_FRAGMENT_NUMBER_MASK, DOT11_SEQUENCE_FRAGMENT_NUMBER_SHIFT,
        DOT11_SEQUENCE_NUMBER_MASK, DOT11_SEQUENCE_NUMBER_SHIFT, DOT11_TAG_DS_PARAMETER_SET,
        DOT11_TAG_RSN, DOT11_TAG_SSID, DOT11_TAG_SUPPORTED_RATES, DOT11_TAG_TIM,
    };
    // The deprecated `Icmp*` aliases (renamed to the explicit `Icmpv4*` names) are
    // re-exported separately so the `#[allow(deprecated)]` exemption stays scoped to
    // just these aliases; the prelude picks them up through `pub use crate::core::*`.
    #[allow(deprecated)]
    pub use crate::{
        Icmp, IcmpAddressMask, IcmpQuotedIpv4, IcmpRouterAdvertisementEntry, IcmpTimestamp,
    };
}

/// Common imports for generated packet tools and examples.
///
/// The prelude includes packet construction and decode types, low-level pcap
/// file helpers, and the high-level wire primitives: [`PacketWire`],
/// [`PacketRecord`], [`PacketTransform`], [`Sniffer`], and [`Transmitter`].
pub mod prelude {
    pub use crate::core::*;
    pub use crate::{
        default_interface, default_interface_in, default_interface_name, derive_pmk, derive_ptk,
        dump_pcap, find_interface, find_interface_in, get_ip_strings, get_ips, get_my_ip,
        get_my_ip_in, get_my_ipv6, get_my_ipv6_in, get_my_mac, get_my_mac_in, interface_for,
        interface_for_in, interfaces, parse_ip_range, parse_numbers, read_pcap, read_pcap_filtered,
        reply_filter, reply_matches, send_packet, send_packets, send_plan, send_recv_packet,
        send_recv_packets, BatchSend, BatchSendEntry, BatchSendRecv, BatchSendRecvEntry,
        BatchSendRecvReport, BatchSendReport, Dot11Metadata, InterfaceAddress, InterfaceInfo,
        Ipv4Range, NetError, PacketBatchSendExt, PacketBatchSendRecvExt, PacketSendExt,
        PacketSendRecvExt, PairwiseTransientKey, PcapError, PcapHeader, PcapLinkType, PcapPacket,
        PcapReader, PcapRecord, PcapRecords, PcapTimestamp, PcapWriter, PcapWriterOptions, Pmk,
        RawSender, ReplyMatcher, SendMode, SendOptions, SendPlan, SendRecv, SendRecvOptions,
        SendRecvReport, SendReport, SendTarget, Sniffer, SocketSend, SocketSender,
        TimestampPrecision, Transmitter, VecPacketSource, WifiDecryptState, WifiMetadata,
        WifiProtectionStatus, WireError, WpaAkm, WpaCipher, WpaCredentialStatus, WpaDecrypt,
        WpaDecryptConfig, WpaDecryptReason, WpaHandshakeStatus, WpaKeyKind, WpaMetadata,
        WpaNetwork, WriteReport,
    };
    pub use crate::{
        BackendKind, BluetoothMetadata, DropAllTransform, DuplicateTransform, IpDefrag,
        IpDefragConfig, IpDefragEvictionReason, IpDefragMetadata, IpDefragOverlapPolicy,
        IpDefragOverlapStatus, IpDefragStats, IpFragment, IpFragmentConfig, IpFragmentFamily,
        IpFragmentMetadata, IpFragmentRange, IpFragmentReason, IpFragmentStats,
        Ipv4DontFragmentPolicy, Ipv4FragmentIdentificationPolicy, Ipv6AtomicFragmentPolicy,
        Ipv6FragmentIdentificationPolicy, MediumMetadata, MemoryPacketWriter, MemoryWrite,
        OpenedPacketSource, OpenedPacketWriter, PacketMetadata, PacketOrigin, PacketRecord,
        PacketSource, PacketTransform, PacketWire, PacketWireBuilder, PacketWireTarget,
        PacketWriter, PassThroughTransform, RadioMetadata, RawSocketWireBuilder, RawSocketWriter,
        SnifferCancel, SnifferHandle, TraceAppendTransform, TransformOutput, TransformTrace,
        IP_DEFRAG_DEFAULT_MAX_AGE, IP_DEFRAG_DEFAULT_MAX_BYTES_PER_DATAGRAM,
        IP_DEFRAG_DEFAULT_MAX_DATAGRAMS, IP_FRAGMENT_MIN_MTU,
    };
}
