//! TLS packet-layer module.
//!
//! Source-backed steps add typed record, handshake, extension, and codepoint
//! behavior while preserving unknown or encrypted bytes as raw payloads.

pub mod alert;
pub mod cipher_suite;
pub mod constants;
pub mod content_type;
pub(crate) mod decode;
pub mod extension;
pub mod handshake;
pub mod layer;
pub mod named_group;
pub mod record;
pub mod signature_scheme;
pub mod vector;
pub mod vectors;
pub mod version;

pub use alert::{TlsAlert, TlsAlertDescription, TlsAlertLevel, TLS_ALERT_LEN};
pub use cipher_suite::{TlsCipherSuite, TlsCipherSuiteList};
pub use content_type::TlsContentType;
pub use extension::{
    TlsAlpnProtocol, TlsAlpnProtocols, TlsCertificateAuthorities, TlsCertificateStatusType,
    TlsCookie, TlsDistinguishedName, TlsEcPointFormat, TlsEcPointFormats, TlsExtensionListContext,
    TlsExtensionType, TlsExtensions, TlsKeyShare, TlsKeyShareContext, TlsKeyShareEntry,
    TlsOcspResponderId, TlsOcspResponderIds, TlsOcspStatusRequest, TlsOidFilter, TlsOidFilters,
    TlsPadding, TlsPreSharedKey, TlsPreSharedKeyContext, TlsPskBinderEntry, TlsPskBinders,
    TlsPskIdentities, TlsPskIdentity, TlsPskKeyExchangeMode, TlsPskKeyExchangeModes,
    TlsRawExtension, TlsRecordSizeLimit, TlsServerName, TlsServerNameList, TlsServerNameType,
    TlsSignatureAlgorithms, TlsSignatureAlgorithmsCert, TlsStatusRequest, TlsStatusRequestBody,
    TlsStatusRequestV2, TlsStatusRequestV2Item, TlsSupportedGroups, TlsSupportedVersions,
    TlsSupportedVersionsContext, TLS_ALPN_PROTOCOL_NAME_LENGTH_LEN,
    TLS_ALPN_PROTOCOL_NAME_LIST_LENGTH_LEN, TLS_CERTIFICATE_AUTHORITIES_LENGTH_LEN,
    TLS_CERTIFICATE_AUTHORITIES_MAX_LEN, TLS_CERTIFICATE_AUTHORITIES_MIN_LEN,
    TLS_CERTIFICATE_STATUS_TYPE_LEN, TLS_CERTIFICATE_STATUS_TYPE_OCSP,
    TLS_CERTIFICATE_STATUS_TYPE_OCSP_MULTI_RESERVED, TLS_CERTIFICATE_STATUS_TYPE_RESERVED,
    TLS_COOKIE_LENGTH_LEN, TLS_COOKIE_MAX_LEN, TLS_COOKIE_MIN_LEN,
    TLS_DISTINGUISHED_NAME_LENGTH_LEN, TLS_DISTINGUISHED_NAME_MAX_LEN,
    TLS_DISTINGUISHED_NAME_MIN_LEN, TLS_EC_POINT_FORMATS_LENGTH_LEN,
    TLS_EC_POINT_FORMAT_ANSIX962_COMPRESSED_CHAR2, TLS_EC_POINT_FORMAT_ANSIX962_COMPRESSED_PRIME,
    TLS_EC_POINT_FORMAT_LEN, TLS_EC_POINT_FORMAT_UNCOMPRESSED, TLS_EXTENSION_HEADER_LEN,
    TLS_EXTENSION_LENGTH_LEN, TLS_EXTENSION_LIST_LENGTH_LEN, TLS_EXTENSION_TYPE_LEN,
    TLS_KEY_SHARE_CLIENT_SHARES_LENGTH_LEN, TLS_KEY_SHARE_ENTRY_HEADER_LEN,
    TLS_KEY_SHARE_GROUP_LEN, TLS_KEY_SHARE_KEY_EXCHANGE_LENGTH_LEN,
    TLS_OCSP_REQUEST_EXTENSIONS_LENGTH_LEN, TLS_OCSP_RESPONDER_ID_LENGTH_LEN,
    TLS_OCSP_RESPONDER_ID_LIST_LENGTH_LEN, TLS_OCSP_RESPONDER_ID_MAX_LEN,
    TLS_OCSP_RESPONDER_ID_MIN_LEN, TLS_OID_FILTERS_LENGTH_LEN, TLS_OID_FILTERS_MAX_LEN,
    TLS_OID_FILTER_MIN_LEN, TLS_OID_FILTER_OID_LENGTH_LEN, TLS_OID_FILTER_OID_MAX_LEN,
    TLS_OID_FILTER_OID_MIN_LEN, TLS_OID_FILTER_VALUES_LENGTH_LEN, TLS_OID_FILTER_VALUES_MAX_LEN,
    TLS_PRE_SHARED_KEY_SELECTED_IDENTITY_LEN, TLS_PSK_BINDERS_LENGTH_LEN,
    TLS_PSK_BINDER_LENGTH_LEN, TLS_PSK_IDENTITIES_LENGTH_LEN, TLS_PSK_IDENTITY_HEADER_LEN,
    TLS_PSK_IDENTITY_LENGTH_LEN, TLS_PSK_IDENTITY_OBFUSCATED_TICKET_AGE_LEN,
    TLS_PSK_KEY_EXCHANGE_MODES_LENGTH_LEN, TLS_PSK_KEY_EXCHANGE_MODE_LEN,
    TLS_PSK_KEY_EXCHANGE_MODE_PSK_DHE_KE, TLS_PSK_KEY_EXCHANGE_MODE_PSK_KE,
    TLS_RECORD_SIZE_LIMIT_LEN, TLS_RECORD_SIZE_LIMIT_MIN, TLS_RECORD_SIZE_LIMIT_TLS12_MAX,
    TLS_RECORD_SIZE_LIMIT_TLS13_MAX, TLS_SERVER_NAME_HEADER_LEN, TLS_SERVER_NAME_LENGTH_LEN,
    TLS_SERVER_NAME_LIST_LENGTH_LEN, TLS_SERVER_NAME_TYPE_HOST_NAME, TLS_SERVER_NAME_TYPE_LEN,
    TLS_SIGNATURE_ALGORITHMS_LIST_LENGTH_LEN, TLS_SIGNATURE_ALGORITHM_LEN,
    TLS_STATUS_REQUEST_V2_ITEM_HEADER_LEN, TLS_STATUS_REQUEST_V2_ITEM_REQUEST_LENGTH_LEN,
    TLS_STATUS_REQUEST_V2_LIST_LENGTH_LEN, TLS_SUPPORTED_GROUPS_LIST_LENGTH_LEN,
    TLS_SUPPORTED_GROUP_LEN, TLS_SUPPORTED_VERSIONS_CLIENT_LENGTH_LEN, TLS_SUPPORTED_VERSION_LEN,
};
pub use handshake::{
    TlsCertificate, TlsCertificateBody, TlsCertificateEntry, TlsCertificateForm,
    TlsCertificateRequest, TlsCertificateRequestBody, TlsCertificateRequestForm,
    TlsCertificateVerify, TlsCertificateVerifyBody, TlsClientCertificateType, TlsClientHello,
    TlsClientHelloBody, TlsEncryptedExtensions, TlsEncryptedExtensionsBody, TlsFinished,
    TlsFinishedBody, TlsHandshake, TlsHandshakeBody, TlsHandshakeHeader, TlsHandshakeType,
    TlsNewSessionTicket, TlsNewSessionTicketBody, TlsNewSessionTicketForm, TlsServerHello,
    TlsServerHelloBody, TLS_CERTIFICATE_ENTRY_LENGTH_LEN, TLS_CERTIFICATE_LIST_LENGTH_LEN,
    TLS_CERTIFICATE_REQUEST_CONTEXT_LENGTH_LEN, TLS_CERTIFICATE_REQUEST_TYPES_LENGTH_LEN,
    TLS_CERTIFICATE_VERIFY_SIGNATURE_LENGTH_LEN,
    TLS_CLIENT_CERTIFICATE_TYPE_DSS_EPHEMERAL_DH_RESERVED,
    TLS_CLIENT_CERTIFICATE_TYPE_DSS_FIXED_DH, TLS_CLIENT_CERTIFICATE_TYPE_DSS_SIGN,
    TLS_CLIENT_CERTIFICATE_TYPE_ECDSA_FIXED_ECDH, TLS_CLIENT_CERTIFICATE_TYPE_ECDSA_SIGN,
    TLS_CLIENT_CERTIFICATE_TYPE_FORTEZZA_DMS_RESERVED,
    TLS_CLIENT_CERTIFICATE_TYPE_RSA_EPHEMERAL_DH_RESERVED,
    TLS_CLIENT_CERTIFICATE_TYPE_RSA_FIXED_DH, TLS_CLIENT_CERTIFICATE_TYPE_RSA_FIXED_ECDH,
    TLS_CLIENT_CERTIFICATE_TYPE_RSA_SIGN, TLS_CLIENT_HELLO_FIXED_LEN,
    TLS_CLIENT_HELLO_LEGACY_VERSION_LEN, TLS_CLIENT_HELLO_RANDOM_LEN, TLS_COMPRESSION_METHOD_NULL,
    TLS_HANDSHAKE_HEADER_LEN, TLS_HANDSHAKE_LENGTH_LEN, TLS_HANDSHAKE_MAX_LENGTH,
    TLS_HANDSHAKE_TYPE_LEN, TLS_NEW_SESSION_TICKET_AGE_ADD_LEN,
    TLS_NEW_SESSION_TICKET_LIFETIME_LEN, TLS_NEW_SESSION_TICKET_NONCE_LENGTH_LEN,
    TLS_NEW_SESSION_TICKET_TICKET_LENGTH_LEN, TLS_SERVER_HELLO_FIXED_LEN,
    TLS_SERVER_HELLO_LEGACY_VERSION_LEN, TLS_SERVER_HELLO_RANDOM_LEN,
};
pub use layer::Tls;
pub use named_group::{TlsNamedGroup, TlsNamedGroupList};
pub use record::{
    TlsHandshakeRecordBody, TlsRecord, TlsRecordBody, TlsRecordHeader, TLS_RECORD_CONTENT_TYPE_LEN,
    TLS_RECORD_HEADER_LEN, TLS_RECORD_LENGTH_LEN, TLS_RECORD_VERSION_LEN,
};
pub use signature_scheme::{TlsSignatureScheme, TlsSignatureSchemeList};
pub use version::{TlsVersion, TlsVersionField};

#[cfg(test)]
mod tests;
