//! Version-neutral IP concepts.

pub mod protocol_numbers;
pub mod traffic_class;

pub(crate) use protocol_numbers::{ip_protocol_summary, ipv6_next_header_summary};
pub use protocol_numbers::{
    IPPROTO_AH, IPPROTO_DSTOPTS, IPPROTO_ESP, IPPROTO_EXPERIMENTAL_1, IPPROTO_EXPERIMENTAL_2,
    IPPROTO_FRAGMENT, IPPROTO_GRE, IPPROTO_HIP, IPPROTO_HOPOPTS, IPPROTO_ICMP, IPPROTO_ICMPV6,
    IPPROTO_IGMP, IPPROTO_IPV6, IPPROTO_IPV6_AH, IPPROTO_IPV6_DSTOPTS, IPPROTO_IPV6_ESP,
    IPPROTO_IPV6_EXPERIMENTAL_1, IPPROTO_IPV6_EXPERIMENTAL_2, IPPROTO_IPV6_FRAGMENT,
    IPPROTO_IPV6_HIP, IPPROTO_IPV6_HOPOPTS, IPPROTO_IPV6_MOBILITY, IPPROTO_IPV6_NO_NEXT,
    IPPROTO_IPV6_ROUTE, IPPROTO_IPV6_SHIM6, IPPROTO_MOBILITY, IPPROTO_NO_NEXT, IPPROTO_OSPF,
    IPPROTO_ROUTE, IPPROTO_SCTP, IPPROTO_SHIM6, IPPROTO_TCP, IPPROTO_UDP,
};
pub use traffic_class::{Dscp, Ecn};
pub(crate) use traffic_class::{DSCP_SHIFT, ECN_MASK};
